- ftw/simplelayout/browser/resources/Overlay.js
- ftw/simplelayout/browser/resources/main.js
- ftw/simplelayout/browser/resources/simplelayout.min.js
Fix cleanup for canceled Blocks.
Fix double fired close events.
Enable scrolling for overlay.
> Overlay fixes.

- ftw/simplelayout/browser/resources/main.js
Fixes #87 
Extend default config with specific settings.
> Make simplelayout configurable through data attributes.

- ftw/simplelayout/browser/resources/main.js
Disable components when no layouts are available.
> Can drag component on empty page.

- ftw/simplelayout/configuration.py
- ftw/simplelayout/testing.py
- ftw/simplelayout/tests/test_simplelayout_view.py
> Make sure page configuration is recursive persistent.

- README.rst
- ftw/simplelayout/browser/blocks/configure.zcml
- ftw/simplelayout/browser/blocks/mapblock.py
- ftw/simplelayout/browser/blocks/templates/mapblock.pt
- ftw/simplelayout/browser/configure.zcml
- ftw/simplelayout/browser/resources/mapblock.js
- ftw/simplelayout/browser/viewlets/configure.zcml
- ftw/simplelayout/browser/viewlets/openlayers.pt
- ftw/simplelayout/browser/viewlets/openlayers.py
- ftw/simplelayout/contents/configure.zcml
- ftw/simplelayout/contents/interfaces.py
- ftw/simplelayout/contents/mapblock.py
- ftw/simplelayout/lawgiver.zcml
- ftw/simplelayout/permissions.zcml
- ftw/simplelayout/profiles/default/jsregistry.xml
- ftw/simplelayout/profiles/default/metadata.xml
- ftw/simplelayout/profiles/default/propertiestool.xml
- ftw/simplelayout/profiles/default/types.xml
- ftw/simplelayout/profiles/default/types/ftw.simplelayout.MapBlock.xml
- ftw/simplelayout/tests/test_load_addable_blocks_view.py
- setup.py
> Mapblock implementation

- ftw/simplelayout/browser/ajax/add.py
- ftw/simplelayout/browser/ajax/addable_blocks_view.py
- ftw/simplelayout/browser/ajax/delete_blocks.py
- ftw/simplelayout/browser/ajax/edit_block.py
- ftw/simplelayout/browser/ajax/fileupload.py
- ftw/simplelayout/browser/ajax/utils.py
The json_response sets the content-type and x-theme-disabled headers for json
responses and dumps the json.
> add json_response helper, which sets response headers

- README.rst
- ftw/simplelayout/browser/provider.py
- ftw/simplelayout/browser/resources/main.js
- ftw/simplelayout/browser/resources/simplelayout.integration.css
- ftw/simplelayout/browser/simplelayout.py
- ftw/simplelayout/browser/templates/structure.pt
- ftw/simplelayout/configuration.py
- ftw/simplelayout/interfaces.py
- ftw/simplelayout/lawgiver.zcml
- ftw/simplelayout/permissions.zcml
- ftw/simplelayout/profiles/default/rolemap.xml
- ftw/simplelayout/tests/test_simplelayout_view.py
This PR also introduces a new permission called ``ChangeLayouts``.
> Implement 2 more ways to change the simplelayout configuration

- ftw/simplelayout/browser/resources/main.js
- ftw/simplelayout/browser/resources/simplelayout.min.js
Client lib master was broken. Update client lib and integration for
synchronized state.
```javascript
simplelayout.attachToolbox()
````
is deprecated.
So use options for attaching a toolbox.
Events are handled globally with a singleton eventEmitter instance.
> Update client lib.

- ftw/simplelayout/browser/ajax/add.py
- ftw/simplelayout/browser/ajax/addable_blocks_view.py
- ftw/simplelayout/browser/configure.zcml
- ftw/simplelayout/configure.zcml
- ftw/simplelayout/contents/interfaces.py
- ftw/simplelayout/interfaces.py
- ftw/simplelayout/tests/test_simplelayout_as_frontpage.py
Also implement addable types for IPloneSiteRoot.
> Make PloneRoot Simplelayoutish

- ftw/simplelayout/browser/resources/Overlay.js
Append submit buttons explicitly to formdata.
> Overlay does not send buttons to backend in internet exploerer.

- ftw/simplelayout/browser/ajax/add.py
- ftw/simplelayout/browser/provider.py
- ftw/simplelayout/browser/resources/main.js
- ftw/simplelayout/browser/templates/structure.pt
- ftw/simplelayout/tests/test_add_block.py
This way we can e.g. redirect to "folder_contents" of the block.
> Add a new block redirect action.

- ftw/simplelayout/browser/blocks/configure.zcml
- ftw/simplelayout/browser/blocks/galleryblock.py
- ftw/simplelayout/browser/blocks/templates/galleryblock.pt
- ftw/simplelayout/browser/blocks/templates/listingblock.pt
- ftw/simplelayout/browser/resources/integration.default.css
- ftw/simplelayout/browser/resources/integration.theme.scss
- ftw/simplelayout/browser/resources/main.js
- ftw/simplelayout/contents/configure.zcml
- ftw/simplelayout/contents/filelistingblock.py
- ftw/simplelayout/contents/galleryblock.py
- ftw/simplelayout/contents/interfaces.py
- ftw/simplelayout/lawgiver.zcml
- ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/ftw.simplelayout.pot
- ftw/simplelayout/permissions.zcml
- ftw/simplelayout/profiles/default/metadata.xml
- ftw/simplelayout/profiles/default/propertiestool.xml
- ftw/simplelayout/profiles/default/rolemap.xml
- ftw/simplelayout/profiles/default/types.xml
- ftw/simplelayout/profiles/default/types/ftw.simplelayout.GalleryBlock.xml
- ftw/simplelayout/profiles/default/workflows.xml
- ftw/simplelayout/tests/builders.py
- ftw/simplelayout/tests/test_galleryblock.py
- ftw/simplelayout/tests/test_load_addable_blocks_view.py
- setup.py
@maethu 
implemented the galleryblock from ftw.contentpage.
could you review?
> Es 133 implementation galleryblock

- ftw/simplelayout/browser/resources/Overlay.js
- ftw/simplelayout/browser/resources/keycode.js
- ftw/simplelayout/browser/resources/main.js
- ftw/simplelayout/profiles/lib/jsregistry.xml
Fixes: #157 
Attach handler for determining if main upload queue is completet.
> Disable closing overlay

- ftw/simplelayout/browser/ajax/add.py
- ftw/simplelayout/browser/ajax/edit_block.py
- ftw/simplelayout/browser/configure.zcml
- ftw/simplelayout/browser/provider.py
- ftw/simplelayout/browser/redirect_to_parent.py
- ftw/simplelayout/profiles/default/types/ftw.simplelayout.FileListingBlock.xml
- ftw/simplelayout/profiles/default/types/ftw.simplelayout.GalleryBlock.xml
- ftw/simplelayout/profiles/default/types/ftw.simplelayout.MapBlock.xml
- ftw/simplelayout/profiles/default/types/ftw.simplelayout.TextBlock.xml
- ftw/simplelayout/profiles/default/types/ftw.simplelayout.VideoBlock.xml
- ftw/simplelayout/tests/test_redirect_to_parent_view.py
- ftw/simplelayout/utils.py
- test-plone-4.3.x.cfg
- Also implement a redirect_ro_parent_view
> Implement getting the current view thru block properties

- ftw/simplelayout/profiles/default/tinymce.xml
@maethu 
closes: https://github.com/4teamwork/bern.web/issues/182
> Add contentpage to tinymces resource types

- README.rst
- ftw/simplelayout/browser/provider.py
- ftw/simplelayout/browser/resources/main.js
- ftw/simplelayout/configuration.py
- ftw/simplelayout/configure.zcml
- ftw/simplelayout/portlets/configure.zcml
- ftw/simplelayout/portlets/portlet.py
- ftw/simplelayout/portlets/templates/portlet.pt
- ftw/simplelayout/tests/test_simplelayout_portlet.py
Implementation of a simple portlet which renders a simpleyout container.
> Make it possible to show blocks in the portlet column

- ftw/simplelayout/browser/resources/Overlay.js
Include plone 5 patterns lib for scanning the form in the overlay.
> Plone 5 widget are not getting initialized.

- ftw/simplelayout/browser/resources/Overlay.js
- ftw/simplelayout/browser/resources/keycode.js
- ftw/simplelayout/profiles/lib/jsregistry.xml
Use jqueryUI's keycode detection.
> Keycodes get overridden through other packages.

- ftw/simplelayout/mapblock/profiles/default/types/ftw.simplelayout.MapBlock.xml
- ftw/simplelayout/profiles/default/types/ftw.simplelayout.ContentPage.xml
- ftw/simplelayout/profiles/default/types/ftw.simplelayout.FileListingBlock.xml
- ftw/simplelayout/profiles/default/types/ftw.simplelayout.GalleryBlock.xml
- ftw/simplelayout/profiles/default/types/ftw.simplelayout.TextBlock.xml
- ftw/simplelayout/profiles/default/types/ftw.simplelayout.VideoBlock.xml
- ftw/simplelayout/tests/test_load_addable_blocks_view.py
> Remove type descriptions and allow overriding them with translations.

- ftw/simplelayout/browser/blocks/templates/galleryblock.pt
> Remove HTML tags in title attribute of the link.

- ftw/simplelayout/browser/blocks/templates/ftw.table.custom.template.pt
> Render the summary in a hidden caption tab.

- ftw/simplelayout/browser/ajax/templates/block_delete_confirmation.pt
- ftw/simplelayout/browser/resources/Overlay.js
- ftw/simplelayout/browser/resources/main.js
- ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/ftw.simplelayout.pot
Make possible to add custom css class for overlay element.
Update german translations.
> Kb overlay customclass

- ftw/simplelayout/browser/blocks/templates/textblock.pt
- ftw/simplelayout/browser/blocks/textblock.py
- ftw/simplelayout/contents/textblock.py
- ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/ftw.simplelayout.pot
- ftw/simplelayout/tests/test_textblock_view.py
- sources.cfg
> Open image of text block in overlay.

- ftw/simplelayout/contents/filelistingblock.py
- ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/ftw.simplelayout.pot
> Add missing labels to file listing block schema.

- ftw/simplelayout/browser/actions.py
- ftw/simplelayout/contents/filelistingblock.py
- ftw/simplelayout/contents/galleryblock.py
- ftw/simplelayout/contents/textblock.py
- ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/ftw.simplelayout.pot
- ftw/simplelayout/tests/test_load_addable_blocks_view.py
> Add missing translations of block actions.

- ftw/simplelayout/browser/resources/integration.default.css
- ftw/simplelayout/browser/resources/integration.theme.scss
> Overlays are not stacked correctly.

- ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po
@maethu 
Fix german translation
> Fix typo in german translation

- ftw/simplelayout/browser/resources/integration.default.css
- ftw/simplelayout/browser/resources/integration.theme.scss
- ftw/simplelayout/contenttypes/browser/templates/galleryblock.pt
@maethu 
Removed the inlinestyles for the galleryblock and handled it over css.
> Remove inlinestyles for galleryblock

- ftw/simplelayout/browser/resources/integration.default.css
- ftw/simplelayout/browser/resources/integration.theme.scss
- ftw/simplelayout/contenttypes/browser/templates/galleryblock.pt
@maethu 
Fix stylingissues in galleryblock.
Old
===
New
===
> Fix stylingissues in galleryblock.

- ftw/simplelayout/contenttypes/behaviors.py
- ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/ftw.simplelayout.pot
@maethu 
Update teaser fieldset description.
> Update teaser fiedescription

- ftw/simplelayout/tests/test_configuration.py
- ftw/simplelayout/tests/test_simplelayout_view.py
Add specific tests for page- and block-config storages.
> add page / block config tests.

- ftw/simplelayout/contenttypes/browser/templates/galleryblock.pt
- ftw/simplelayout/contenttypes/browser/templates/textblock.pt
- ftw/simplelayout/contenttypes/browser/textblock.py
@maethu 
- Remove title attribute on galleryblock image
- Remove title attribute on textblock image and teaser url
> Es 902 accessibility

- ftw/simplelayout/contenttypes/browser/templates/galleryblock.pt
- ftw/simplelayout/contenttypes/browser/templates/textblock.pt
- ftw/simplelayout/contenttypes/browser/textblock.py
Reverts 4teamwork/ftw.simplelayout#272
> Revert "Es 902 accessibility"

- docs/HISTORY.txt
- ftw/simplelayout/contenttypes/browser/filelistingblock.py
- ftw/simplelayout/contenttypes/browser/templates/galleryblock.pt
- ftw/simplelayout/contenttypes/browser/templates/listingblock.pt
> Show hint on empty listing and galeryblock.

- setup.py
Adds `ftw.upgrade` to `setup.py`.
closes #340
> Add ftw.upgrade

- ftw/simplelayout/browser/resources/Overlay.js
- sources.cfg
> Fix form validation in overlay.

- docs/HISTORY.txt
- ftw/simplelayout/browser/resources/videoblock.js
Closes https://github.com/4teamwork/winterthur.web/issues/103
> Display default youtube player controls

- docs/HISTORY.txt
- ftw/simplelayout/browser/resources/integration.theme.scss
Closes https://github.com/4teamwork/winterthur.web/issues/101
> Fix missing toolbar on videoblocks

- docs/HISTORY.txt
- ftw/simplelayout/mapblock/browser/mapblock.py
- ftw/simplelayout/mapblock/browser/resources/mapblock.js
- ftw/simplelayout/mapblock/browser/resources/mapblock.scss
- ftw/simplelayout/mapblock/browser/templates/map_input.pt
- ftw/simplelayout/mapblock/browser/templates/mapblock.pt
Also display map always in a 2 / 3 ratio.
> Fix several IE11 issues and caching issues

- docs/HISTORY.txt
- ftw/simplelayout/browser/resources/theming.toolbar-icons.scss
- setup.py
✅ Depends on https://github.com/4teamwork/ftw.theming/pull/63
🚧 Depends on https://github.com/4teamwork/ftw.simplelayout/pull/387
> Fix scss linting errors

- docs/HISTORY.txt
- ftw/simplelayout/mapblock/upgrades/20161101142706_fix_auth_condition_on_mablock_js/jsregistry.xml
- ftw/simplelayout/mapblock/upgrades/20161101142706_fix_auth_condition_on_mablock_js/upgrade.py
> Enable mapblock.js for anonymous users.

- docs/HISTORY.txt
- ftw/simplelayout/browser/resources/integration.theme.scss
Closes https://github.com/4teamwork/ftw.simplelayout/issues/397
> Styling issues

- docs/HISTORY.txt
This has been forgotten to be added in https://github.com/4teamwork/ftw.simplelayout/pull/414
> Add missing history entry.

- docs/HISTORY.txt
- ftw/simplelayout/browser/resources/ftw.simplelayout.js
- ftw/simplelayout/js/src/simplelayout/Layoutmanager.js
- ftw/simplelayout/js/src/simplelayout/Simplelayout.js
- ftw/simplelayout/js/test/spec/integration.test.js
- ftw/simplelayout/js/test/spec/layoutmanager.test.js
Closes https://github.com/4teamwork/ftw.simplelayout/issues/120
> Conditionally display move action on toolbar on the layout

- README.rst
- docs/HISTORY.txt
Closes https://github.com/4teamwork/ftw.simplelayout/issues/424
> Include theme compatibility hint in readme.

- docs/HISTORY.txt
- ftw/simplelayout/browser/resources/integration.theme.scss
- ftw/simplelayout/contenttypes/profiles/default/metadata.xml
- ftw/simplelayout/upgrades/20170428171243_install_iframefix/upgrade.py
- setup.py
Use iframefixes from ftw.iframefix
Closes https://github.com/4teamwork/ftw.simplelayout/issues/431
> Install ftw.iframefix

- docs/HISTORY.txt
- ftw/simplelayout/browser/resources/integration.theme.scss
Depends on https://github.com/4teamwork/ftw.iframefix/pull/5
> Make iframe fixes compatible with ftw.iframefix 2.0.

- ftw/simplelayout/browser/resources/main.js
- ftw/simplelayout/js/README.md
The new events are
- 'block-added'
- 'block-edited'
- 'sl-state-updated'
> Provide additional DOM events on document.

- docs/HISTORY.txt
- ftw/simplelayout/browser/ajax/add.py
- ftw/simplelayout/browser/resources/ftw.simplelayout.js
- ftw/simplelayout/browser/resources/main.js
- ftw/simplelayout/js/src/simplelayout/Block.js
- ftw/simplelayout/js/test/spec/block.test.js
- package.json
The anchors are not handled by the block content.
So the anchor was just visible after a page refresh.
> Add anchor to new created blocks.

- docs/HISTORY.txt
- ftw/simplelayout/configuration.py
Unfortunately, we cannot write a test for this.
> Add support for "ftw.gopip".

- docs/HISTORY.txt
- ftw/simplelayout/mapblock/browser/resources/mapblock.js
It now works as expected with even with tabs ;-)
> Fix loading google / geo maps in overlays within a tab.

- ftw/simplelayout/browser/ajax/edit_block.py
- ftw/simplelayout/contenttypes/profiles/default_plone5/types/ftw.simplelayout.TextBlock.xml
- Use plone message factory for awoiding import problem.
- Add missing cropping behaviors.
> Plone 5: message factory and cropping

- docs/HISTORY.txt
- ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/fr/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/ftw.simplelayout.pot
- ftw/simplelayout/staging/templates/baseline_viewlet.pt
- ftw/simplelayout/tests/test_staging.py
> Staging: Add link to working copies in warning message.

- docs/HISTORY.txt
- ftw/simplelayout/mapblock/browser/resources/mapblock.js
This is the backport of the pull request https://github.com/4teamwork/ftw.simplelayout/pull/528 onto the 1.x branch.
> Backport pull request #528

- docs/HISTORY.txt
- ftw/simplelayout/mapblock/browser/resources/mapblock.js
Backport for #530 -> allow zoomlevel and maplayers for behaviours
> Backport for #530 onto 1.x

- docs/HISTORY.txt
- ftw/simplelayout/staging/staging.py
Refer to https://github.com/4teamwork/ftw.events/pull/51 for a full description of the problem.
> Fix EventBasic timezone conflict when applying working copies

- docs/HISTORY.txt
- ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/fr/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/ftw.simplelayout.pot
- ftw/simplelayout/staging/templates/baseline_viewlet.pt
- ftw/simplelayout/staging/templates/workingcopy_viewlet.pt
- ftw/simplelayout/staging/viewlets.py
- ftw/simplelayout/tests/test_staging.py
> Port #557 improved linking between baseline working copy to 2.x 

- docs/HISTORY.txt
- ftw/simplelayout/contenttypes/upgrades/20191029182332_add_missing_image_scale/upgrade.py
> Fix upgrade step for Plone 4.

- docs/HISTORY.txt
- ftw/simplelayout/contenttypes/browser/templates/listingblock.pt
- ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/fr/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/ftw.simplelayout.pot
Gallery part of fix for https://github.com/4teamwork/izug.organisation/issues/1725
> Translate 'Upload files here'

- docs/HISTORY.txt
- ftw/simplelayout/contenttypes/browser/dropzone.py
closes https://github.com/4teamwork/izug.organisation/issues/1754
> To create a file, get the correct file type from the schema.

- docs/HISTORY.txt
- ftw/simplelayout/locales/de/LC_MESSAGES/plone.po
- ftw/simplelayout/locales/plone.pot
part of https://github.com/4teamwork/izug.organisation/issues/1745
> Add ftw.simplelayout portal_types translations to plone domain.

- ftw/simplelayout/aliasblock/contents/aliasblock.py
- ftw/simplelayout/testing.py
- ftw/simplelayout/tests/test_alias_block.py
This PR is part of the new alias block implementation and adds the reference widget used for selecting the block whose content will, later on, be rendered within the alias block.
> Replace title with reference widget.

- ftw/simplelayout/aliasblock/contents/aliasblock.py
- ftw/simplelayout/tests/test_alias_block.py
This will be needed to implement a custom constraint, so ContentPages containing an aliasblock are not referable.
> Add custom selectable class in preparation for linking sl pages.

- docs/HISTORY.txt
- ftw/simplelayout/browser/ajax/configure.zcml
- ftw/simplelayout/browser/ajax/templates/add.pt
- ftw/simplelayout/browser/ajax/templates/edit_block_form.pt
- ftw/simplelayout/browser/ajax/templates/viewletmanager.pt
- ftw/simplelayout/interfaces.py
I'll need this change in order to load some map related code in the alias block to make referenced maps work.
> Add viewletmanager for block add/edit form in order to load custom code.

- docs/HISTORY.txt
- ftw/simplelayout/aliasblock/browser/templates/aliasblock.pt
- ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/fr/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/ftw.simplelayout.pot
> Show linked page title on aliasblock.

- docs/HISTORY.txt
- ftw/simplelayout/aliasblock/browser/aliasblock.py
- ftw/simplelayout/aliasblock/browser/templates/aliasblock.pt
- ftw/simplelayout/aliasblock/contents/aliasblock.py
- ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/fr/LC_MESSAGES/ftw.simplelayout.po
- ftw/simplelayout/locales/ftw.simplelayout.pot
I also added another block as possible AliasBlock reference --> ftw.contacts.MemberBlock.
> Update AliasBlock releated translations.

- ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po
Partly resolves https://4teamwork.atlassian.net/browse/OGB-576
> Fix typo in aliasblock.

- docs/HISTORY.txt
- ftw/simplelayout/browser/resources/main.js
> Backport of: #645: Fix layout/column in aliasblock results in failure

- docs/HISTORY.txt
- ftw/simplelayout/aliasblock/profiles/default/metadata.xml
> Aliasblock Remove explicit dependency on sl contenttypes.
