4teamwork/ftw.simplelayout

ftw/simplelayout/browser/resources/main.js
It's in the context of a block, and we shop the url with the component actions (addable blocks)
@bierik 
Closes #73
=> Remove edit/delete endPoint - it make no sense in the context of simplelayout

ftw/simplelayout/browser/resources/main.js
It no longer tries to load the `sl-ajax-addable-blocks-view` on non simplelayout pages. 
```
Traceback (innermost last):
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module ftw.simplelayout.browser.ajax.addable_blocks_view, line 23, in __call__
Module ftw.simplelayout.browser.ajax.addable_blocks_view, line 28, in addable_blocks
TypeError: ('Could not adapt', <PloneSite at /Plone>, <InterfaceClass Products.CMFPlone.interfaces.constrains.ISelectableConstrainTypes>)
```
=> Prevent loading simplelayout if there is no simlelayout container.

ftw/simplelayout/configure.zcml, ftw/simplelayout/lawgiver.zcml
Adding a page requires the "add" action group.
Adding files, listingblocks and textblocks requires the "edit" action group,
becuase it is in fact considered editing the content of the page.
=> lawgiver: map permissions.

ftw/simplelayout/profiles/default/ftw.simplelayout.setuphandlers.txt
=> Remove setuphandlers marker file.

ftw/simplelayout/browser/resources/main.js
Calculating height with javascript is a general fail and the usage was
not done properly as well. So the feature is going to be disabled and
replaced with pure CSS --> https://github.com/4teamwork/ftw.simplelayout/issues/126.
=> Remove match height feature.

ftw/simplelayout/browser/resources/Overlay.js
Handle form as submitted when callback is able to proceed.
Fixed #123
=> Fix cancel overlay on server validation error.

ftw/simplelayout/configure.zcml, ftw/simplelayout/handlers.py, ftw/simplelayout/tests/test_copy_contentpage.py
After a simplelayout page has copied, update the PageState with the new block uids. 
So the layout and blocks remain on their position.
=> Implement copy support for simplelayout pages.

ftw/simplelayout/browser/resources/Overlay.js
Tinymce fails on loading when opening the edit view.
Trigger an additional save solves the problem.
=> Tinymce does not load on new created block.

ftw/simplelayout/browser/resources/main.js
```getActiveBlock``` is deprecated for getting the current block. Use
the ```$(this)``` context instead.
=> Calling a server action produces an error.

ftw/simplelayout/browser/resources/main.js
Check for response content type header. Accept only ```application/json```.
An error would look like this: ```Uncaught Error: Bad response
[content-type: text/html;charset=utf-8]```
=> Bad response for components breaks simplelayout.

ftw/simplelayout/browser/provider.py, ftw/simplelayout/browser/resources/main.js
This way we can decide if we have to initialize simplelayout, or not.
=> Add canEdit option.

ftw/simplelayout/browser/resources/main.js
@maethu @bierik 
Fixed issue: The colorbox needs to reinitialize after editing a gallery block
=> Fix issue: The colorbox needs to reinitialize after editing a gallery block

ftw/simplelayout/browser/configure.zcml, ftw/simplelayout/browser/uploadcapable.py, ftw/simplelayout/tests/test_uploadcapable.py
@maethu Uploading images in filelistingblock will create a file instead an image
closes: https://github.com/4teamwork/bern.web/issues/183
=> Uploading images in filelistingblock will create a file instead an image

ftw/simplelayout/browser/resources/theming.toolbar-icons.scss, ftw/simplelayout/resources.zcml
When ftw.theming is installed and the standard iconset is font-awesome, the default icons for blocks are replaced by the font-awesome icons.
Since font-awesome is only avaiable in ftw.theming's icons file we cannot its variables but need to extend existing classes and redefine the before pseudo-class.
/ @maethu @bierik
=> use font-awesome type icons in toolbar.

ftw/simplelayout/profiles/lib/cssregistry.xml
Due to 4teamwork/ftw.simplelayout#159 the dependencies for the client
lib are moved.
=> Update dependencies for client lib.

ftw/simplelayout/browser/configure.zcml
=> Only register file factory adapter for quickupload when c.quickupload is

ftw/simplelayout/browser/ajax/add.py, ftw/simplelayout/browser/ajax/edit_block.py, ftw/simplelayout/tests/test_block_statusmessage.py
Imho they are not necessary for simplelayout blocks, since we not reload the page...
So we got two possibilities to handle this issue.
First: Display the statusmessages
Second: Do not generate the statusmessages, or do not display the statusmessages. 
This PR imlements the second option.
=> Do not create, or consume generated status messages for blocks.

ftw/simplelayout/browser/resources/Overlay.js
Due to https://github.com/4teamwork/bern.web/issues/204 the submit and
cancel events has to get handeled separately.
=> Expose submit and cancel events.

ftw/simplelayout/browser/provider.py, ftw/simplelayout/tests/test_simplelayout_view.py
When rendering a simplelayout page, blocks referenced in the config of
the page may or may not be accessible for the current user.
There may be different reasons why it is not available:
- the block is not visible to the current user by security (View)
- the block is not visible because of an expiration date
- the block is not visible because of a publication date
- the block is not visible because it was deleted
- it is a staging environment where the page has been published but not
yet all blocks.
This fixes an error in the provider template when referenced blocks are unavailable:
```python
LocationError: ({u'uid': u'76efd9fd9f574bef8f7e661404654456'}, 'url')
```
=> provider: skip unavailable blocks when rendering.

ftw/simplelayout/profiles/default/types/ftw.simplelayout.ContentPage.xml, ftw/simplelayout/profiles/default/types/ftw.simplelayout.FileListingBlock.xml, ftw/simplelayout/profiles/default/types/ftw.simplelayout.GalleryBlock.xml, ftw/simplelayout/profiles/default/types/ftw.simplelayout.MapBlock.xml, ftw/simplelayout/profiles/default/types/ftw.simplelayout.TextBlock.xml, ftw/simplelayout/profiles/default/types/ftw.simplelayout.VideoBlock.xml
The IReferenceable behavior adds the objects to the reference catalog.
We need this in order to lookup objects by UUID.
=> Enable IReferenceable on all types.

ftw/simplelayout/browser/blocks/base.py, ftw/simplelayout/browser/blocks/configure.zcml, ftw/simplelayout/browser/blocks/filelistingblock.py, ftw/simplelayout/browser/blocks/galleryblock.py, ftw/simplelayout/browser/blocks/templates/galleryblock.pt, ftw/simplelayout/browser/blocks/templates/listingblock.pt, ftw/simplelayout/browser/blocks/templates/textblock.pt, ftw/simplelayout/browser/blocks/textblock.py, ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout.pot, ftw/simplelayout/tests/test_galleryblock.py, ftw/simplelayout/tests/test_listingblock.py, ftw/simplelayout/tests/test_textblock_view.py
This causes some blocks to be empty which results in the edit toolbar not being shown. This is circumvented by rendering a hint about the emptiness of the block.
=> Don't render the block heading if there is no title.

ftw/simplelayout/browser/resources/main.js
In Plone 5 the base tag is no longer supported. So define the addable
blocks url and save endpoint explicitly.
=> Addable blocks are not shown properly in Plone 5.

ftw/simplelayout/browser/resources/theming.toolbox-icons.scss
In ftw.theming the font-awesome icon selectors have changed for fixing an selector ordering conflict with the default icon.
Also the "icon-missing" color was changed to fuchsia.
This change fixes the extends selector so that icons work again and it also adds an icon-missing icon in fuchsia. We really want to have icons for all blocks ;-).
/ @bierik @maethu
=> update ftw.theming compatible toolbox icons.

ftw/simplelayout/browser/ajax/addable_blocks_view.py, ftw/simplelayout/browser/dynamic_scss_resources.py, ftw/simplelayout/browser/resources/integration.default.css, ftw/simplelayout/resources.zcml, ftw/simplelayout/utils.py
Hide block types from add menu with ftw.theming and without ftw.theming. 
:exclamation: the `!important` is necessary, since the `authoring.css` from plone also has a !important.
=> Add scss factory, which hides all block types from the add menu.

ftw/simplelayout/configuration.py
The obj in the handler may, or may not acquisition wrapped.
=> Getting the request in events the bullet proof way.

ftw/simplelayout/browser/client/web/js/app/simplelayout/Simplelayout.js
Only add class "sl-block-dragging" when a component is dragging.
=> Block draggable indicator is added when dragging a layout.

ftw/simplelayout/profiles/default/types/ftw.simplelayout.ContentPage.xml
As discussed with @jone ftw.simplelayout should only provide basic behaviors.
This means the decision, which dexterity metadata behaviors should be active on a contentpage should delegated to the integration.
=> Remove behaviors, which are not necessary

ftw/simplelayout/browser/dynamic_scss_resources.py
ftw.theming has introduced the DynamicSCSSResource class, which should
be used for optimized production caching.
See https://github.com/4teamwork/ftw.theming/pull/13
=> ftw.theming: use dynamic SCSS resource.

ftw/simplelayout/browser/resources/Overlay.js
Fixes https://github.com/4teamwork/bern.web/issues/460
Remove animation effect for overlays.
=> On some devices the overlay animation is lagging.

ftw/simplelayout/behaviors.zcml, ftw/simplelayout/configure.zcml, setup.py
- use ftw.autofeature
- remove ``installed collective.dexteritytextindexer`` condition for ``BlockSearchableTextIndexer``
- fix description of ``ISimpleleayout`` behavior
- also provide behaviors for Plone 5 :exclamation: 
@maethu 
/cc @buchi
=> use ftw.autofeature; minor fixes

ftw/simplelayout/browser/resources/Overlay.js
Fixes #229 
Mapblock has triggered an overlay submit event instead of asynchronously
loading the location suggestions. The overlay's load method does not
instantly show the overlay. So if the speed is set to 0 make the overlay
visible manually before loading the overlay.
=> Mapblock searchresults not working.

ftw/simplelayout/browser/configure.zcml, ftw/simplelayout/browser/simplelayout.py, ftw/simplelayout/tests/test_simplelayout_view.py
This is useful to query the available block types in restricted python scripts.
=> Expose the available block types on the simplelayout view.

ftw/simplelayout/browser/resources/integration.theme.scss, ftw/simplelayout/contenttypes/browser/templates/galleryblock.pt
Crop images to 130 x 130 Pixel by default. 
This way we can make sure every images uses the same amount of space.
=> Improve gallery listing - crop images.

ftw/simplelayout/configuration.py, ftw/simplelayout/tests/test_configuration.py, ftw/simplelayout/tests/test_simplelayout_view.py
:construction: includes #254
The new ``synchronize_page_config_with_blocks`` function synchronizes the page config with the actually existing blocks.
It removes no longer existing blocks and adds existing blocks which are not in the page configuration.
Along with this function various helper functions were added:
- ``columns_in_config``
- ``flattened_block_uids``
- ``block_uids_in_page``
- ``block_uids_missing_in_config``
Also the **default page state was changed**!
We need to have a valid default page state with at least one column for this to work.
Therefore I've changed the default page state to have a `default` container with a one-column layout.
=> add synchronize_page_config_with_blocks and relatives.

ftw/simplelayout/configuration.py, ftw/simplelayout/tests/builders.py, ftw/simplelayout/tests/test_builders.py, ftw/simplelayout/tests/test_configuration.py, ftw/simplelayout/tests/test_simplelayout_view.py
:construction: includes #255, relates to #205 
The `.with_blocks` method of the page state builder accepts one or more block builders.
On blocks added with the `.with_blocks` method, `.within(page)` is automatically called for placing the blocks in the page.
After the page is created, the blocks are created too and the page configuration is synced.
=> Add .with_blocks to page state builder

ftw/simplelayout/contenttypes/browser/galleryblock.py, ftw/simplelayout/tests/test_galleryblock.py
Image title may contain umlauts.
=> Fix UnicodeDecodeError on galleryblock listing.

ftw/simplelayout/browser/resources/main.js
The ```blockInserted``` event was binded before the simplelayout DOM
structure got serialized. So every time when a block was
inserted a new Overlay was loaded. Because the URL for getting the form
was empty the whole page got downloaded.
Sorry for that :disappointed:
=> Page get downloaded several times on reload through XHR.

ftw/simplelayout/browser/ajax/delete_blocks.py, ftw/simplelayout/browser/ajax/templates/block_delete_confirmation.pt, ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout.pot
- Show internal content, which refers on the current content.
- Make deletion of the block possible.
=> Implement link integrity for blocks.

ftw/simplelayout/browser/resources/main.js
Depends on https://github.com/OneGov/plonetheme.onegovbear/pull/69
=> Disable ajax spinner for toolbox.

ftw/simplelayout/browser/resources/main.js
Reverts 4teamwork/ftw.simplelayout#265
The theme, or plone should decide how the spinner is working.
=> Revert "Disable ajax spinner for toolbox."

ftw/simplelayout/configuration.py, ftw/simplelayout/tests/test_configuration.py
This makes it possible to have multiple simplelayout views with different slots on one object. 
Example:
1. Default simplelayout view (only one slot -> `default`
2. Special search view with one slot -> `search`
The old behavior always reassigned the new store, which means if someone edited the simplelayout page with the `search` slot, the informations of the `default` slot was doomed.
The new implementation does now an `update` instead. This way only the sots used in the DOM are updated. 
For this new usecase I also hat to change the behavior what happen if a block was not present in store. 
**Before:** Get all columns and append the block to the first column. 
**New:** Get the first column of the `default` slot.
=> Change the "store" page configuration behavior

ftw/simplelayout/configuration.py, ftw/simplelayout/tests/test_configuration.py
With #268 we introduced updating the storage, instead of new reassign the whole storage.
@jone sry I missed this one.
=> The default page configuration should be persistent, since it will be updated later.

ftw/simplelayout/browser/provider.py, ftw/simplelayout/tests/test_simplelayout_view.py
This fixes an issue if the block state was somehow stored in a broken manner.
=> Filter block states with no `uid` key.

ftw/simplelayout/contenttypes/browser/textblock.py, ftw/simplelayout/tests/test_teaser_behavior.py
This fixes an `AttributeError` if the internal target no longer exists.
=> Also check for an existing target on internal refs (teaser).

ftw/simplelayout/indexer.py
This may cause problems with collective.indexing and is btw. not necessary.
=> Do not trigger a catalog search to get the new searchable text of a page.

ftw/simplelayout/handlers.py, ftw/simplelayout/testing.py, ftw/simplelayout/tests/test_handlers.py
Fix an issue if the page_config is only partial persistent after retrieving a versioned contentpage (I don't know why it is partial persistent, but it is). Serializing a persistent dict or map is not possible and we get a json encode error.
If the ``unwrap_persistance`` method gets a partial persistent config, it will stop unwrap.
This PR will fix this. The unwrapper will unwrapp all possible elements, doesn't matter if it is already unwrapped or not.
=> Fix unwrap_persistance handler method

ftw/simplelayout/contenttypes/configure.zcml, ftw/simplelayout/contenttypes/profiles/default/jsregistry.xml, ftw/simplelayout/contenttypes/profiles/default/metadata.xml, ftw/simplelayout/contenttypes/upgrades/20151203153127_make_video_block_available_for_anonymous/jsregistry.xml, ftw/simplelayout/contenttypes/upgrades/20151203153127_make_video_block_available_for_anonymous/upgrade.py
The videoblock is broken for anonymous users because the videoblock.js is not available for anonymous users.
This PR will fix this.
@maethu do we need already upgradesteps?
=> Make videoblock.js available for anonymous users too

ftw/simplelayout/browser/resources/main.js
If the sidebar container is not rendered the javascript throws an error
and stops further execution of the script. So the layout restrictions
should be defined serverside dynamically for the diffrent views.
=> Default layout restrictions only works for bern.web project.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/configure.zcml, ftw/simplelayout/contenttypes/profiles/default/types/Plone_Site.xml, ftw/simplelayout/contenttypes/upgrades/20160113155920_configure_addable_types/types/Plone_Site.xml, ftw/simplelayout/contenttypes/upgrades/20160113155920_configure_addable_types/upgrade.py, ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout-manual.pot, ftw/simplelayout/locales/ftw.simplelayout.pot
No uprade step:
On a customer installation we already had to configure this, otherwise simplelayout did not work properly, that's why I provide no upgrade step for this change
=> Add Simplelayout view as possible front page layout + addable types on the plone site

docs/HISTORY.txt, ftw/simplelayout/browser/resources/integration.default.css, ftw/simplelayout/browser/resources/integration.theme.scss, ftw/simplelayout/contenttypes/browser/filelistingblock.py
- Implement some sane default withs for columns.
- Do not sort the table with js
=> Use default table listing for the listingblock styles.

docs/HISTORY.txt, ftw/simplelayout/browser/dynamic_scss_resources.py
This happens accentually, if ftw.simplelayout is in the PATH, but no installed.
=> Fix simplelayout dynamic scss resource, so it does not return invalid code if the selector is empty.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/integration.theme.scss
Fixes https://github.com/OneGov/plonetheme.onegovbear/issues/110
The gridsystem works with relative positioned containers. The right
column comes after the content column to the portletcolumn on the right
overlapps the content. To make sure the toolbar is always on top
apply a fixed z-index.
=> Right column overlapps the toolbar.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/galleryblock.py, ftw/simplelayout/contenttypes/browser/textblock.py, ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout.pot, ftw/simplelayout/tests/test_textblock_view.py
Automatically add "enlarged picture" to links, which opens in a overlay. 
This changes improves the accessiblity (screen reader).
=> Implement better image alt text for galleryblock and textblock.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/leadimage.py
The cachekey currently includes the full URL to the image.
This is problematic since the URL may change depending how the site is
accessed (VirtualHostMonster, port tunneling).
The second problem is that the cache key does not include the page. This
may lead to the wrong image beeing displayed when multiple pages are
modified at the exact same time.
Since this is cache is probably a premature optimization I'm just
removing it. We can implement a new one when we are in need.
=> Remove leadimage cache key.

docs/HISTORY.txt, ftw/simplelayout/browser/provider.py, ftw/simplelayout/portlets/portlet.py, ftw/simplelayout/tests/test_simplelayout_portlet.py, ftw/simplelayout/tests/test_simplelayout_view.py
On `REQUEST.set('disable_border', '1')` the simplelayout toolset is not loaded. 
This is a default plone feature. 
This also affects the simplelayout portlet:
If the portlet is empty and disable_border=1 do not show the portlet.
=> Respect disable_border key in request and do not load simplelayout if present.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/profiles/default/tinymce.xml, ftw/simplelayout/mapblock/profiles/default/tinymce.xml
Configure TinyMCE so that the page and the blocks are linkable in TinyMCE and the folderish types (page, listing and gallery blocks) can be opened for linking their contents.
=> Configure TinyMCE resource types.

ftw/simplelayout/contenttypes/browser/textblock.py
Closes https://github.com/4teamwork/bl.web/issues/74
Changing the scale behavior in
https://github.com/4teamwork/ftw.simplelayout/commit/23b6cbbf5e8302637dcf06db55e3d2afc6ccc49a
for simplelayout textblock images may be confusing for the user.
The user is responsible himself to upload proper images with fitting aspect ratio.
=> Reset default scale behavior for textblock images.

docs/HISTORY.txt, ftw/simplelayout/browser/provider.py, ftw/simplelayout/browser/resources/integration.theme.scss, ftw/simplelayout/browser/templates/structure.pt, ftw/simplelayout/contenttypes/contents/filelistingblock.py, ftw/simplelayout/contenttypes/contents/galleryblock.py, ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout-manual.pot, ftw/simplelayout/locales/ftw.simplelayout.pot, ftw/simplelayout/tests/test_galleryblock.py, ftw/simplelayout/tests/test_listingblock.py
Hidden blocks will not be shown on its simplelayout container if the user does not have the permission to edit content.
Users allowed to edit the block will see the block anyway (highlighted).
This is not a security feature, the block and its content can still be accessed if the path is known.
=> Some blocks can be hidden now.

ftw/simplelayout/browser/resources/integration.theme.scss
Closes https://github.com/4teamwork/bl.web/issues/93
=> Fix gallery spacing in gallery grid.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/contents/filelistingblock.py, ftw/simplelayout/tests/test_listingblock.py
Files has no WF on simplelayout sites, since the files belongs directly to site itself. 
Thus we remove the `Review State` column by default. 
This also fixes a issue if the review state column is active and workflow for files is present:
```
2016-04-08 08:26:59 ERROR Zope.SiteErrorLog 1460096819.890.249324806379 http://localhost:8080/platform2/politik-und-behorden/direktionen/finanz-und-kirchendirektion/finanzverwaltung/finanzkennzahlen/downloads/edit.json
Traceback (innermost last):
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module z3c.form.form, line 224, in __call__
Module ftw.simplelayout.browser.ajax.edit_block, line 59, in render
Module ftw.simplelayout.utils, line 20, in …
```
=> Remove "Review State" column from file listing block.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/leadimage.py, ftw/simplelayout/tests/test_leadimage.py
When looking for the lead image of a SL-container, we now also take
gallery blocks with images into account.
=> Lead-Image: support gallery blocks.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/leadimage.py, ftw/simplelayout/tests/test_leadimage.py
We need to support having images only in the portlet slot.
This changes looks at first in the default slot, but then looks in all slots for images.
=> Lead-Image: support all slots.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/integration.theme.scss
When the overlay is open, we need to disable the main scrollbar, so that scrolling in the overlay does not scroll the main page.
/cc @bierik
=> hide main scrollbar when overlay is open.

ftw/simplelayout/browser/resources/integration.theme.scss
Quick fix for https://github.com/4teamwork/bl.web/issues/84
=> Fix zindex order.

ftw/simplelayout/browser/resources/main.js
To make it possible to identify the different overlay loaded by simplelayout
mark the overlays with a unique css class.
=> Mark different overlay with classes.

docs/HISTORY.txt, ftw/simplelayout/mapblock/browser/resources/mapblock.js
Even after scrolling the mouse cursor and the openlayers cursor are at the same position.
=> Fix mouse pointer position according to openlayers pointer.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/integration.theme.scss, ftw/simplelayout/contenttypes/browser/templates/textblock.pt, ftw/simplelayout/contenttypes/contents/textblock.py, ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout.pot
Also move image related fields into a image fieldset
=> Add image caption for textblock

docs/HISTORY.txt, ftw/simplelayout/browser/resources/integration.theme.scss
Fix height of empty SLPortlet - this makes it easier to drop blocks into it. 
**Portlet and 4 Col (1 img per row)**
**2 Col (2 img per row)**
**1 Col (4 img per row)**
---
Closes #326
=> Improve listing of galleryblock + Fix height of empty SimplelayoutPortlet

docs/HISTORY.txt, ftw/simplelayout/browser/provider.py, ftw/simplelayout/browser/resources/integration.theme.scss, ftw/simplelayout/contenttypes/browser/templates/textblock.pt, ftw/simplelayout/contenttypes/contents/textblock.py, ftw/simplelayout/tests/test_textblock_view.py
bases on #331 
This way it's possible to place a title only block without additional spacing.
Also show the empty block warning, only if the block is really empty.
=> Remove bottom margin for TextBlocks containing only a title

docs/HISTORY.txt, setup.py
Adding a filelisting-block failed on IE11.
See https://github.com/zopefoundation/z3c.form/pull/37.
=> Update z3c.form to 3.2.9 to fix IE11 bug when adding a filelisting-block.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/main.js
Closes https://github.com/4teamwork/bl.web/issues/162
DOM modifications from the simplelayout are not tracked
from the browser as a new page. So we have to trigger
a manual history change.
Tested with 
`http://localhost`,
`http://localhost?key=value`,
`http://localhost?key=value&anohterkey=antohervalue`,
`http://localhost#hash`,
`http://localhost?key=value#hash`,
`http://localhost?key=value&anohterkey=antohervalue#hash`
=> Implement statekeeper for tracking DOM changes.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/integration.theme.scss
Closes https://github.com/4teamwork/bl.web/issues/214
In IE it is not possible to track events on wrapping elements
containing an iframe.
=> Prevent iframe from stopping event bubbling in IE.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/RequestTracker.js, ftw/simplelayout/profiles/lib/jsregistry.xml, ftw/simplelayout/upgrades/20160525161113_register_request_tracker_javascript/jsregistry.xml, ftw/simplelayout/upgrades/20160525161113_register_request_tracker_javascript/upgrade.py
The request tracker tracks URLs which are not banned
through a white and blacklist system. When a request lasts
longer than a specific threshold (300ms by default) the root element
will be extended with a marker class (ajax-loading)
=> Implement request tracker.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/integration.theme.scss
This fixes a issue, when it was no longer possible to re-add a layout after deleting the last one.
=> Add min-height to empty Simplelyout portlet.

ftw/simplelayout/handlers.py, sources.cfg
The portal type `FormFolder` has been turned into a simpleyalyout block in the amnesty.ch project. Deleting such a form folder causes an exception because of a handler in `ftw.simplylayout`. This handler tries to adapt the parent of the form folder with `IPageConfiguration`. This will fail if the parent of the form folder is a folder.
See https://basecamp.com/2768704/projects/9428894/todos/238322959
=> Fix exception when form folder is deleted.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/integration.theme.scss
The images in a simplelayout block should not float if they are full width.
This issue breaks the bullets of the listing for example.
Before:
After:
=> Fix floating images on mobile view.

docs/HISTORY.txt, ftw/simplelayout/locales/collective.quickupload.pot, ftw/simplelayout/locales/de/LC_MESSAGES/collective.quickupload.po
The title of the quickupload overlay is not translated properly in german.
This PR will translate the overlay title.
Before
-------
After
-----
=> Translate quickupload title in overlay for filelistings and galleryblocks.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/integration.theme.scss
Also fixes iframeblock boundaries:
Before:
After:
=> Use zindex system from ftw.theming

docs/HISTORY.txt, ftw/simplelayout/contenttypes/Extensions/install.py, ftw/simplelayout/contenttypes/__init__.py, ftw/simplelayout/contenttypes/configure.zcml, ftw/simplelayout/contenttypes/profiles/uninstall/jsregistry.xml, ftw/simplelayout/contenttypes/profiles/uninstall/propertiestool.xml, ftw/simplelayout/contenttypes/profiles/uninstall/rolemap.xml, ftw/simplelayout/contenttypes/profiles/uninstall/tinymce.xml, ftw/simplelayout/contenttypes/profiles/uninstall/types.xml, ftw/simplelayout/contenttypes/profiles/uninstall/types/Plone_Site.xml, ftw/simplelayout/contenttypes/profiles/uninstall/workflows.xml, ftw/simplelayout/mapblock/Extensions/install.py, ftw/simplelayout/mapblock/__init__.py, ftw/simplelayout/mapblock/configure.zcml, ftw/simplelayout/mapblock/profiles/uninstall/jsregistry.xml, ftw/simplelayout/mapblock/profiles/uninstall/propertiestool.xml, ftw/simplelayout/mapblock/profiles/uninstall/rolemap.xml, ftw/simplelayout/mapblock/profiles/uninstall/tinymce.xml, ftw/simplelayout/mapblock/profiles/uninstall/types.xml, ftw/simplelayout/mapblock/profiles/uninstall/workflows.xml, ftw/simplelayout/tests/test_uninstall.py
This PR adds adds uninstall profiles for the following extras:
- mapblock
- contenttypes
=> Uninstall profile for mapblock and contenttypes extras

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/configure.zcml, ftw/simplelayout/contenttypes/browser/jbot/z3c.form.browser.orderedselect_input.js, ftw/simplelayout/contenttypes/browser/overrides/orderedselect_input.js
In IE11 it's not possible to manipulate a select (multiple) after modifying the text of a option.
=> Add IE11 fix for InAndOutWidget Javascript.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/integration.theme.scss
See https://github.com/4teamwork/winterthur.web/issues/176
⚠️  Depends on https://github.com/4teamwork/plonetheme.blueberry/pull/90
The toolbox label should be treated as an overlay
because it should overlap everything on the page but
the editoverlay
=> Fix toolbox label zindex

ftw/simplelayout/browser/resources/integration.theme.scss
See https://github.com/4teamwork/winterthur.web/issues/174
The author is responsible to choose the right amount of columns to make the page good looking
Before:
After:
=> Fix word break inside listing block tables

docs/HISTORY.txt, ftw/simplelayout/browser/resources/integration.theme.scss
@maethu I added an expand icon for colorbox images.
=> Add Expand icon for colorbox images.

docs/HISTORY.txt, ftw/simplelayout/profiles/lib/rolemap.xml, ftw/simplelayout/upgrades/20160816120005_configure_change_layout_permissions/rolemap.xml, ftw/simplelayout/upgrades/20160816120005_configure_change_layout_permissions/upgrade.py
Sets permission for change layout, site admin & manager can now have permission to change the layout.
Also includes an upgrade step for the new permissions.
closes #342
=> Set permissions for change layout

docs/HISTORY.txt, ftw/simplelayout/browser/resources/main.js
The colorbox does not get initialized when adding
a textblock with an image.
=> Fix image overlay in textblock

README.rst, docs/HISTORY.txt, ftw/simplelayout/migration.py
The `migration.py` provides a set of inplace migrators for migrating AT
types (`ftw.contentpage`) to DX types (`ftw.simplelayout`).
The migration must be executed in an upgrade step in the integration
package / project, because:
- a migration upgrade step can't be put in neither the old
package (`ftw.contentpage`) nor the new package (`ftw.simplelayout`),
because neither can be sure that the other package is present at a
specific upgrade step (version)
- in a project the types may have had additional fields bevore (schema
extender) and / or after (additional behaviors)
- such migrations should be tested well and implemented carefully for a
specific project
Because of those reasons, we provide pre-configured inplace migrators
for common simplelayout types for various packages here, but …
=> Support migration from ftw.contentpage.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/leadimage.py, ftw/simplelayout/opengraph/og_sl_page.py
Before, one had to call `_get_image`, an internal method, in order to
update the view state so that `has_image` and `get_scale` would work as
expected. This is not how public methods should work.
By refactoring it this way I try to not change the public interface but
fix the state issues by auto-loading internally when not yet done.
=> Make leadimages "has_image" and "get_scale" usable.

development.cfg, docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/galleryblock.py, ftw/simplelayout/contenttypes/contents/galleryblock.py, ftw/simplelayout/tests/test_galleryblock.py
The galleryblock now has 2 sort options just like the file listingblock.
=> Add sort options for image galleries

ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po
@maethu Rename Teaser function to Link function. Apparently Teaser isn't widely understood.
=> rename teaser function to link function

docs/HISTORY.txt, ftw/simplelayout/browser/resources/integration.theme.scss, ftw/simplelayout/browser/resources/main.js
The drop animation changed the background color of the dropped
element to `#fff`. The background-color should not be done using
style attribute because overriding these styles requires an `!important`
statement in the CSS.
=> Fix drop animation

README.rst, docs/HISTORY.txt, ftw/simplelayout/behaviors.zcml, ftw/simplelayout/browser/simplelayout.py, ftw/simplelayout/browser/templates/simplelayout.pt, ftw/simplelayout/interfaces.py, ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout.pot, ftw/simplelayout/tests/test_content_types.py, ftw/simplelayout/tests/test_contentpage.py
Adds a checkbox for contentpages which allows a user to decide whether the title of the contentpage is displayed or not.
This works with the new `IContentPageShowTitle` behavior.
See: https://github.com/4teamwork/winterthur.web/issues/312
=> Add show_title checkbox for contentpage

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/templates/videoblock_vimeo.pt, ftw/simplelayout/contenttypes/browser/templates/videoblock_youtube.pt, ftw/simplelayout/contenttypes/contents/videoblock.py, ftw/simplelayout/tests/test_videoblock.py
The other blocks already have an optional title.
=> Add optional title to the video block (disabled by default).

docs/HISTORY.txt, ftw/simplelayout/browser/resources/integration.theme.scss, ftw/simplelayout/contenttypes/browser/templates/textblock.pt
@maethu I added an additional div which allows me to place the icon relative to the image, since it only contains the image instead of the complete content with caption.
=> fix icon with image description

docs/HISTORY.txt, ftw/simplelayout/contenttypes/contents/textblock.py, ftw/simplelayout/locales/fr/LC_MESSAGES/collective.quickupload.po, ftw/simplelayout/locales/fr/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout.pot
Adds description text for the image section in the textblock, `description_image_alt_text` and `description_image_clickable` are available in EN & DE & FR.
closes #374
=> Add textblock descriptions

docs/HISTORY.txt, ftw/simplelayout/interfaces.py, ftw/simplelayout/lawgiver.zcml, ftw/simplelayout/permissions.zcml, ftw/simplelayout/tests/test_contentpage.py, ftw/simplelayout/tests/test_contentpage_behavior.py, ftw/simplelayout/upgrades/20160914172633_protect_show_hide_title_field/rolemap.xml, ftw/simplelayout/upgrades/20160914172633_protect_show_hide_title_field/upgrade.py
I thought calling the permission this way makes more sense, since we are protecting it from getting hidden :-)
=> Protect new show/hide title behavior.

docs/HISTORY.txt, ftw/simplelayout/migration.py
When creating a news folder (ftw.news) or an events folder (ftw.events), listing blocks are created automatically within this folders. Since the migration does not trigger the events which create those blocks we create them explicitly in the inplace migration.
Requires:
- ✅  https://github.com/4teamwork/ftw.news/pull/68
- ✅ https://github.com/4teamwork/ftw.events/pull/10
=> Extend inplace migrator to create listing blocks.

docs/HISTORY.txt, ftw/simplelayout/browser/ajax/add.py, ftw/simplelayout/contenttypes/browser/filelistingblock.py
By not instantiating page template objects in methods but in class definition scope we give Chameleon a chance to cache the compile template, speeding up everything.
=> Support Chameleon caching.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/integration.theme.scss, ftw/simplelayout/browser/resources/videoblock.js, ftw/simplelayout/contenttypes/browser/videoblock.py
This makes videoblocks containing youtube video automatically resize to the available space given by their parent element without changing the width/height ratio.
This way there are no longer any black bars on the side of the block when the available space is bigger than the video itself.
=> Auto resize youtube-videoblocks

README.rst, docs/HISTORY.txt, ftw/simplelayout/browser/ajax/configure.zcml, ftw/simplelayout/browser/ajax/edit_block.py, ftw/simplelayout/browser/resources/main.js, ftw/simplelayout/tests/sample_types.py, ftw/simplelayout/tests/test_inner_edit_block.py, ftw/simplelayout/tests/test_simplelayout_view.py
For example edit a file directly in a FilelistingBlock.
This view works almost like the block edit view, the difference is, that
the inner_edit.json view returns the rendered html of its parent (the Block).
FYI:
I'm gonna use this feature in the ftw.sliderblock first.
=>  Implement a inner_edit.json view, which allows us to edit an item in a folderish block.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/main.js
The main reason for this is the Plone file widget which causes some browsers to trigger the validation when the user wants to replace the file. The validation is triggered when the user clicks the button to select a file from the filesystem and he has to click it a second time for the file selector to open.
=> Disable inline validation of the Plone forms in the overlay.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/galleryblock.py, ftw/simplelayout/tests/test_galleryblock.py
The bug caused the gallery block to fail (not able to render its content) when the block contained image objects having umlauts in their title.
=> Fix a bug in gallery block.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/profiles/default/metadata.xml, setup.py
- Move ``ftw.referencewidget`` dependency to ``contenttypes`` extras, since it is only used for the content types subpackage.
- Remove ``plone.formwidget.contenttree`` dependency, as it is not used at all because it was replaced with ``ftw.referencewidget``.
// cc @tschanzt
=> cleanup reference widget dependencies.

docs/HISTORY.txt, ftw/simplelayout/behaviors.zcml, ftw/simplelayout/contenttypes/behaviors.py, ftw/simplelayout/contenttypes/contents/filelistingblock.py, ftw/simplelayout/contenttypes/contents/galleryblock.py, ftw/simplelayout/contenttypes/profiles/default/types/ftw.simplelayout.FileListingBlock.xml, ftw/simplelayout/contenttypes/profiles/default/types/ftw.simplelayout.GalleryBlock.xml, ftw/simplelayout/contenttypes/upgrades/20161220143319_move_option_to_hide_a_block_to_a_behavior/types/ftw.simplelayout.FileListingBlock.xml, ftw/simplelayout/contenttypes/upgrades/20161220143319_move_option_to_hide_a_block_to_a_behavior/types/ftw.simplelayout.GalleryBlock.xml, ftw/simplelayout/contenttypes/upgrades/20161220143319_move_option_to_hide_a_block_to_a_behavior/upgrade.py, ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/fr/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout.pot
This way the option can easily be added to other simplelayout block types, like the addressblock from "ftw.addressblock".
=> Move option to hide a block to its own behavior.

docs/HISTORY.txt, ftw/simplelayout/browser/provider.py
When a block could not be rendered, the log / console did only contain
"Could not render block" and the error message, but not the traceback.
By using LOG.exception the full traceback is logged too.
=> Log traceback too when a block cannot be rendered.

docs/HISTORY.txt, ftw/simplelayout/browser/anchors.py, ftw/simplelayout/browser/configure.zcml, ftw/simplelayout/browser/resources/integration.theme.scss, ftw/simplelayout/contenttypes/contents/textblock.py, ftw/simplelayout/contenttypes/profiles/default/tinymce.xml, ftw/simplelayout/contenttypes/profiles/uninstall/tinymce.xml, ftw/simplelayout/contenttypes/upgrades/20170106151929_configure_page_to_contain_anchors/tinymce.xml, ftw/simplelayout/contenttypes/upgrades/20170106151929_configure_page_to_contain_anchors/upgrade.py, ftw/simplelayout/tests/test_anchors.py
In order to support anchors in the same content page, but over multiple
blocks, these changes are necessary:
- Enable anchors on content pages.
- Let the content page provide the anchors of it's text blocks.
- Change the priamry-field of text-blocks from "image" to "text" in
order to be able to extract the anchors from the textfield.
- Disable the "anchors"-tab in the link dialog of TinyMCE, because it
does only list local anchors of the same textfield, but when using
simplelayout it is more confusing because the anchors of the other
textblocks on the same page are missing.
In order to set an anchor, select the current page in the "internal" tab (by going up in the path bar), and then select the anchor at the right hand.
=> provide support for anchors within the same page.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/templates/textblock.pt, ftw/simplelayout/tests/test_textblock_view.py
🚧 Please merge https://github.com/4teamwork/ftw.colorbox/pull/11 and release `ftw.colorbox` 1.3 first.
Extend the textblock with the "data-caption" attribute which can hold the caption rendered in the colorbox (requires "ftw.colorbox" 1.3).
=> Improve caption of the textblock's colorbox.

docs/HISTORY.txt, ftw/simplelayout/mapblock/browser/templates/mapblock.pt
The problem is a change in the behavior how string expressions are evaluated in TAL (possibly due to "ftw.chameleon":
```
obj.some_url = 'http://bla.com/blubber?key=value&key2=value'
string: ${obj/some_url}
> http://bla.com/blubber?key=value&amp;key2=value
python: obj.some_url
> http://bla.com/blubber?key=value&key2=value
```
=> Fix map block not showing the Google maps.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/ftw.simplelayout.js, package.json
Removing the shim config, the library no longer assumes that handlebars is installed. Handlebars is now shipped with the simplelayout library.
Closes https://github.com/4teamwork/ftw.simplelayout/issues/419
@jone could you please test this with ftw.book
=> Include handlebars in distributed library

docs/HISTORY.txt, ftw/simplelayout/configuration.py, ftw/simplelayout/tests/test_configuration.py
When removing the last layout from a slot, we want the slot to be restored to the defaults, whatever that is.
It should not destroy states of other slots though.
/cc @mbaechtold
=> Restore slot defaults when removing last layout.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/RequestTracker.js
The current approach to get rid of the spinner seems not to work properly.
Trying to unbind the `ajaxStart` event does not work in all cases.
So according to https://api.jquery.com/ajaxStart/,
> If $.ajax() or $.ajaxSetup() is called with the global option set to false, the .ajaxStart() method will not fire.
setting the `global` option to `false` never triggers the `ajaxStart` event.
=> Prevent plone ajax spinner from being shown.

docs/HISTORY.txt, ftw/simplelayout/mapblock/profiles/default/types/Plone_Site.xml, ftw/simplelayout/mapblock/profiles/uninstall/types/Plone_Site.xml
When `ftw.simplelyout[mapblock]` is installed the MapBlock can now be added to plone site per default.
We don't want an upgrade step for this because we don't want to change how existing deployments handle the MapBlock.
=> Make MapBlock addable on plone site

docs/HISTORY.txt, ftw/simplelayout/configuration.py, ftw/simplelayout/tests/test_ordering.py, ftw/simplelayout/upgrades/20170321145512_update_ordering_of_existing_objects/upgrade.py
By synchronizing the simplelayout block order to Plone's ordered container, the catalog can sort blocks by their simplelayout order when using the objPositionInParent sort index.
=> Support Plone ordered container for sl blocks.

docs/HISTORY.txt, ftw/simplelayout/browser/anchors.py, ftw/simplelayout/tests/test_anchors.py
No longer rely on TinyMCE for the anchor extraction because it contains a bug when an empty value is searched for anchors (see https://github.com/plone/Products.TinyMCE/pull/153).
=> Improve anchor extraction.

ftw/simplelayout/testing.py
This is not necessary since _everything_ is loaded by `z3c.autoinclude` a statement above.
=> testing: remove duplicate ZCML loading.

docs/HISTORY.txt, ftw/simplelayout/browser/anchors.py, ftw/simplelayout/tests/test_anchors.py
lxml raises a XMLSyntaxError if an empty string is passed.
=> Make anchor extraction more robust.

docs/HISTORY.txt, ftw/simplelayout/browser/configure.zcml, ftw/simplelayout/browser/simplelayout.py, ftw/simplelayout/tests/test_simplelayout_view.py
The method `addable_block_types` on the simplelayout view is not in use and is therefore removed.
---
As I am customizing the `simplelayout-view` in my package I wanted to switch from `allowed_attributes` to `allowed_interface` so that I can inherit the configuration and do not need to update on new attributes in the future.
But I then came to the impression that the method `addable_block_types` was not used at all; the toolbar seems to work fine without.
@maethu please verify and confirm that this method is actually not used before merging this pull request!
=> Remove "addable_block_types".

ftw/simplelayout/browser/resources/ftw.simplelayout.js, ftw/simplelayout/browser/resources/integration.theme.scss, ftw/simplelayout/js/src/simplelayout/Toolbar.js
See https://github.com/4teamwork/edubsch.policy/issues/15
All the delimiters were visible even when the corresponding
action is disabled. So bind the delimiter to the action by using
a border instead of an additional delimiter DOM node.
=> Fix toolbar delimiter styling.

docs/HISTORY.txt, ftw/simplelayout/configuration.py, ftw/simplelayout/tests/test_ordering.py
When blocks on the site root are ordered, errors occured because the site root has a different ordering implementation than folders.
=> Fix ordering error on Plone site root.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/RequestTracker.js
Setting ajaxSetup.global to `false` is disabling every ajax event.
As described here https://api.jquery.com/ajaxSend/ the `ajaxSend` event is canceled as well.
So the request tracker was not working since https://github.com/4teamwork/ftw.simplelayout/pull/427 because all ajax events has been canceled.
First step is to remove the ajaxSetup.global setting to `false`.
Second step is to unbind the ajax event listeners from the kss.js
Two things are important here:
1. The RequestTracker.js has to come after the kss so that the listener is unbind properly
2. The unbind function has to be wrapped in a jQuery.ready callback because the kss.js is doing so as well
Third step is to bind our own ajax events to track all requests relevant for showing the spinner.
=> Disable kss spinner.

ftw/simplelayout/tests/test_add_block.py, ftw/simplelayout/tests/test_block_statusmessage.py, ftw/simplelayout/tests/test_delete_block.py, ftw/simplelayout/tests/test_edit_block.py, ftw/simplelayout/tests/test_galleryblock.py, ftw/simplelayout/tests/test_inner_edit_block.py, ftw/simplelayout/tests/test_listingblock.py, ftw/simplelayout/tests/test_opengraph.py, ftw/simplelayout/tests/test_simplelayout_view.py
The testbrowser has changed:
after opening a static document (open_html) it is no longer possible to continue with clicking in the loaded document, since the browser is missing state such as an URL and the static driver does not support making requests.
The correct solution is to use `.parse()` instead of `.open_html()` so that the driver does not change and later requests are done with the original driver.
I have also simplified some tests.
=> update tests to be compatible with newest testbrowser.

docs/HISTORY.txt, ftw/simplelayout/migration.py
Those changes were made during the (still ongoing) edubs migration.
This PR adds handler for `two column` and `two column with top row` layouts. It will generate an appropriate new simplelayout style layout for each and move the blocks based on the Slot marker interfaces.
=> Simplelayout upgrade improvements

docs/HISTORY.txt, ftw/simplelayout/portlets/portlet.py
This might happen if there are other portlet manager, e.g. from `ftw.footer`.
```
ERROR portlets Error while determining renderer availability of portlet ('context' '/ai/platform/verwaltung/ratskanzlei' u'simplelayout-portlet'): local variable 'portlet_container' referenced before assignment
Traceback (most recent call last):
File "/Users/mbaechtold/.buildout/eggs/plone.portlets-2.2-py2.7.egg/plone/portlets/manager.py", line 117, in _lazyLoadPortlets
isAvailable = renderer.available
File "/Users/mbaechtold/.buildout/eggs/ftw.simplelayout-1.17.0-py2.7.egg/ftw/simplelayout/portlets/portlet.py", line 32, in available
if self.has_blocks():
File "/Users/mbaechtold/.buildout/eggs/ftw.simplelayout-1.17.0-py2.7.egg/ftw/simplelayout/portlets/portlet.py", line 44, in has_blocks
if …
```
=> Fix UnboundLocalError in the simplelayout portlet.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/contents/galleryblock.py, ftw/simplelayout/tests/test_galleryblock.py
The new sorting options are position in parent, id and portal type. Just like the file listing block. In fact, the same vocabulary holding the sorting options is used for the file listing block and the gallery block now.
=> Add more sorting options to the gallery block.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/contents/galleryblock.py, ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/fr/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout-manual.pot, ftw/simplelayout/locales/ftw.simplelayout.pot, ftw/simplelayout/tests/test_galleryblock.py
Until now the sort options were based on the columns of the file listing block. If the colums were customized, unwanted sort option would have been applied to the gallery block.
=> Use a static vocabulary for the sort options of the gallery block.

docs/HISTORY.txt, ftw/simplelayout/tests/test_utils.py, ftw/simplelayout/utils.py
This is needed when setting the view name with "ftw.inflator".
=> Handle view names in unicode strings.

docs/HISTORY.txt, ftw/simplelayout/browser/templates/layout.pt
The change introduces an additional wrapper `div` with class `sl-columns`. 
This significantly improves the styling possibilities. 
For example:
- It's possible to define a background-color for all columns
- It's possible to manipulate the floating grid
This change may break stylings of ftw.simplelyout < 1.19.x
Also #428 introduced a layout wrapper. 
Example integration:
https://github.com/4teamwork/stadtwerk.web/pull/75
=> Wrap columns with container.

docs/HISTORY.txt, ftw/simplelayout/tests/builders.py
The content page builder now only synchronises page config if the page contains blocks.
This is relevant in combination with "ftw.activity" and caused a "changed" activity to be recorded, in addition to the regular "created" activity.
=> Improve content page builder.

docs/HISTORY.txt, ftw/simplelayout/mapblock/browser/configure.zcml, ftw/simplelayout/mapblock/browser/mapblock.py, ftw/simplelayout/mapblock/browser/resources/mapblock.js, ftw/simplelayout/mapblock/browser/templates/map_input.pt, ftw/simplelayout/mapblock/browser/templates/mapblock.pt, ftw/simplelayout/mapblock/browser/widget.py, ftw/simplelayout/mapblock/contents/mapblock.py
This PR introduces two new features:
- Store the zoom level per block
- Store the chosen maplayer per block.
Bugfix:
- No longer register maplayers multiple times.
- Delete mapblock JS error. 
Info:
The zoom level was kind of implemented before, but it did not work, this is why there is a hack implemented for this purpose. --> https://github.com/4teamwork/ftw.simplelayout/compare/mle-map-zoom-layer?expand=1#diff-145524684bb7a847c44b606522518698R52
As the comment suggests, I'm not able to fix this in a better way, since it should already work. 
In action:
=> Store the zoom level and the chosen map layer per mapblock. 

docs/HISTORY.txt, ftw/simplelayout/mapblock/contents/mapblock.py
This results in having only 1 tab, instead of two.
=> Move title and show_title field into the coordinates schemata on MapBlock.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/galleryblock.py, ftw/simplelayout/contenttypes/browser/templates/galleryblock.pt, ftw/simplelayout/contenttypes/profiles/default/propertiestool.xml, ftw/simplelayout/contenttypes/profiles/uninstall/propertiestool.xml, ftw/simplelayout/upgrades/20180323111432_add_new_gallery_block_image_scaling/propertiestool.xml, ftw/simplelayout/upgrades/20180323111432_add_new_gallery_block_image_scaling/upgrade.py
When an image in a galleryblock was deleted and replaced with another image
with the same name, the image would not reload in the colorbox overlay because
of image caching. By getting a scale url for each image in the overlay this is
now fixed, since it forces a reload of the image each time.
This is an edge case, and will rarely occur.
=> Always get scaled image when opening colorbox overlay to fix caching issue

README.rst, docs/HISTORY.txt, ftw/simplelayout/configure.zcml, ftw/simplelayout/tests/test_trash.py, ftw/simplelayout/trash.py, setup.py
Lets ftw.simplelayout automatically integrate with ftw.trash.
ftw.trash by default requires the "Add portal content" permission on the parent of an object in order to restore the object. For simplelayout blocks we want a different behavior: since we consider blocks to be part of the content of their page, restoring blocks should only work when the user has the "Modify portal content" permission. We wouldn't want users to be able to restore blocks of published pages, the user would need to retract or revise the page first.
The integration configures ftw.simplelayout to check for the "Modify portal content" permission whenever a user tries to restore a block.
=> Integrate with ftw.trash.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/main.js
This implements falling back on the base tag if there is one. 
This will work until plone 5, plone 5 no longer has a base-tag. This issue will be fixed within the plone 5.1.x branch (good solution)
PLUS:
Add missing event parameter. --> Fixes FF
Resolves #477
=> Quick fix sl baseurl + Fix problem in FF

README.rst, docs/HISTORY.txt, ftw/simplelayout/configure.zcml, ftw/simplelayout/restapi/configure.zcml, ftw/simplelayout/restapi/services.py
This implements a plone.restapi endpoint, with which you can synchronize the pages config with the existing blocks. This is needed after adding new blocks to a sl content page. Otherwise the blocks are added but are not visible in the FrontEnd.
=> Synchronize page config with blocks plone.restapi integration

ftw/simplelayout/browser/resources/integration.theme.scss
Fix the image-cropper image limit validation message with the blueberry marketing theme.
The marketing theme does hide the document-first heading. Thus, the limit-validation message doesn't have enough space to display and will be overlapped by the cropping area.
Before:
After:
=> Fix image cropper styling with blueberry marketing theme.

docs/HISTORY.txt, ftw/simplelayout/images/cropping/browser/cropping.py, ftw/simplelayout/images/cropping/browser/templates/cropping.pt, ftw/simplelayout/tests/test_cropping.py
Fix a caching issue where the cropping overlay have showed the old image after uploading a new one.
Before:
After:
=> Fix a caching issue in cropping overlay

docs/HISTORY.txt, ftw/simplelayout/interfaces.py, ftw/simplelayout/tests/test_image_configuration.py, ftw/simplelayout/upgrades/20181002124534_fix_missing_value_for_image_limits_and_ratios/upgrade.py
This PR fixes the broken blocks after setting no value to `image_limits` or `image_cropping_aspect_rations`.
Before: 
After:
fixes: #488
=> Add missing_value attribute to the `image_limits` and `image_cropping_aspect_ratios` interface

README.rst, docs/HISTORY.txt, ftw/simplelayout/configure.zcml, ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/fr/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout.pot, ftw/simplelayout/staging/configure.zcml, ftw/simplelayout/staging/interfaces.py, ftw/simplelayout/staging/staging.py, ftw/simplelayout/staging/templates/baseline_viewlet.pt, ftw/simplelayout/staging/templates/workingcopy_viewlet.pt, ftw/simplelayout/staging/viewlets.py, ftw/simplelayout/tests/builders.py, ftw/simplelayout/tests/test_staging.py, setup.py
This pull request implements a staging toolset for staging simplelayout content pages.
- This is not batteries included: the staging implementation needs to be integrated on project level, since it is usually hooked up with a workflow, which is implemented in integration code on project level.
- The working copy is created by copying the content page with all content-relevant children, but not recursively including content pages. This allows for staging of root-level pages with tons of subpages.
- The integration code can decide wether the working copy is created in-place or in a centralized folder.
- The integration code can decide wether it is possible to have multiple working copies concurrently - there is no code for handling conflicts though.
- The staging is implemented for …
=> Implement staging for simplelayout pages

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/templates/videoblock_youtube_nocookie.pt, ftw/simplelayout/contenttypes/browser/videoblock.py, ftw/simplelayout/contenttypes/contents/videoblock.py, ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/tests/test_videoblock.py
- More DSGVO compatible (only 5 cookies :-D).
- As iframe - no youtplayer since that one loads a like 20 cookies.
=> Add support for www.youtube-nocookie.com video urls.

docs/HISTORY.txt, ftw/simplelayout/staging/staging.py, ftw/simplelayout/utils.py
- Currently it's used to get the owner of the content.
- adop_roles is not enough, since the catalog still queries with the wrong parameter
- with need both unrestrictedSearchResults and adop_roles to get the object.
=> Implement unrestricted_uuidToObject to get the infos for the staging viewlet, regardless of the workflow.

docs/HISTORY.txt, ftw/simplelayout/staging/staging.py, ftw/simplelayout/tests/test_staging.py
If we have a textblock on the baseline with a link to a child-page of the baseline, creating a working copy of the baseline failed because:
- We are patching the _tree on the baseline when copy/pasting it as working copy.
- When pasting the working copy, plone.app.linkintegrity verifies the links, implemented as paste event handler.
- The link checker then tries to find the sub page (as the copied block has a link to the sub page) but fails, since the sub page is not in the _tree of the baseline at this moment; it will apear later again on cleanup. This results in a traversal error.
Solution:
Move reverting the _tree patch to a temporary IObjectCopiedEvent subscriber,  which is triggered right after inserting the new object. The event subscriber reverts the _tree and unregisters itself. …
=> Staging: fix an error where a sub page link broke staging.

ftw/simplelayout/staging/staging.py, ftw/simplelayout/tests/test_staging.py
In Plone 5, `id` is a field now that has a side effect when it is set: it is not possible to set it to the current value as it will append `-1` because the value is already in use.
Also: use the name-from-title behavior for files and images in order to maintain the same IDs as with Plone 4.
=> Fix staging for Plone 5

sources.cfg
The branch "mle-plone-5.1.x" no longer exists.
=> Install "ftw.referencewidget" from the master branch.

ftw/simplelayout/behaviors.zcml, ftw/simplelayout/images/cropping/configure.zcml
eliminates `WARNING plone.behavior Specifying 'for' in behavior 'Hide block' if no 'factory' is given has no effect and is superfluous.`
=> Remove superfluous "for" of behavior declarations.

ftw/simplelayout/browser/ajax/utils.py, ftw/simplelayout/contenttypes/browser/configure.zcml, ftw/simplelayout/contenttypes/browser/dropzone.py, ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/fr/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout.pot, ftw/simplelayout/testing.py, ftw/simplelayout/tests/assets/world.txt, ftw/simplelayout/tests/test_dropzone_upload.py
The @@dropzone-upload is implemented for file listing blocks and gallery blocks. It expects a MIME multipart request with a "file" and the normal CSRF authenticator token. In file listing blocks it creates a "File", in galleries it creates an "Image" (if the uploaded file is of an image type).
=> Implement dropzone upload backend.

test-plone-4.3.x.cfg
The newer versions of collective.geo packages seem incompatible with Plone 4.
=> Fix tests by downgrading collective.geo packages.

docs/HISTORY.txt, test-plone-4.3.x.cfg
A new release from collective.z3cform.datagridfield (1.5.0) has been cut. This one is no longer Plone 4 compatible.
=> Fix plone 4 build by pinning collective.z3cform.datagridfield to 1.4.0.

ftw/simplelayout/contenttypes/profiles/default/types/ftw.simplelayout.ContentPage.xml, ftw/simplelayout/contenttypes/profiles/default/types/ftw.simplelayout.FileListingBlock.xml, ftw/simplelayout/contenttypes/profiles/default/types/ftw.simplelayout.GalleryBlock.xml, ftw/simplelayout/contenttypes/profiles/default/types/ftw.simplelayout.VideoBlock.xml
The commit `abc8` mistakenly removed IReferenceable in plone4. In consequence references were not added to the reference catalog. This adds it again plus a test showing that it is working again.
=> Revert commit removing IReferenceable and add tests

docs/HISTORY.txt, ftw/simplelayout/mapblock/browser/resources/mapblock.js
This fixes a problem in `ftw.addressblock` (which is based on the JavaScript of the map block): until now, the map did not load when editing the address block directly (not in the overlay, but in the tab of the edit view of the address block itself).
=> Fix mapblock.js

docs/HISTORY.txt
I forgot to add the changelog in https://github.com/4teamwork/ftw.simplelayout/pull/526
This adds a changelog for the reverted abc8.
=> Add changelog for adding IReferenceable

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/templates/galleryblock.pt, ftw/simplelayout/contenttypes/browser/templates/listingblock.pt, ftw/simplelayout/contenttypes/browser/templates/textblock.pt
Using macros and slots allow for easy customization:
- the templates now define a `main` macro
- the templates now define slots such as `title`, `dropzone`, `body`
We'll use that for customizing the title in `ftw.book`.
=> Add macros and slots to block views for easy customization.

docs/HISTORY.txt, ftw/simplelayout/mapblock/browser/resources/mapblock.js
This will be used for ftw.addressblock to work correctly.
The selector looks for an id starting with `field-widget` because otherwise, it would also select the widgets wrapper div. To get the zoomlevel / maplayer we filter for ending with. Together with the starting filter, we can get all zoomlevel / maplayer widgets from or not from a behaviour.
This is in conjunction with https://github.com/4teamwork/ftw.addressblock/pull/25
=> Allow map preferences for behaviours

docs/HISTORY.txt, ftw/simplelayout/mapblock/browser/resources/mapblock.js
On plone 5 we don't have the same tab structure in forms as in plone 4 anymore. This lead the mapblock to not initialising the map when clicking on a tab. To fix this we use new selectors for plone 5 and fallback to plone 4 selectors if no tabs could be found.
=> Fix mapblock.js for plone 5

docs/HISTORY.txt, ftw/simplelayout/mapblock/browser/templates/map_input.pt
The string expression results in having a `&amp;` in the url right before the api key argument, which themselves results having no api key delivered to google maps. 
- Tested with plone 4.3 (no Chameleon)
- Tested with plone 5.1.5 Chameleon 2.25
- Tested with plone 5.1.5 Chameleon 3.3
=> Fix html entities in data-googlejs url.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/profiles/default_plone5/registry.xml, ftw/simplelayout/contenttypes/upgrades/20190614100752_move_js_to_registry_for_contenttypes/registry.xml, ftw/simplelayout/mapblock/profiles/default_plone5/registry.xml, ftw/simplelayout/mapblock/upgrades/20190614114616_move_mapblock_js_from_legacy_to_its_own_bundle/registry.xml, ftw/simplelayout/mapblock/upgrades/20190614114616_move_mapblock_js_from_legacy_to_its_own_bundle/upgrade.py
- Add upgrade step for the mapblock js (legacy -> own bundle)
- Add `<value key="compile">False</value>`  -> There's no requireJS in our JS files. 
- Fix resource name of mapblock.js
Before:
- videoblock / mapblock in legacy bundle
After:
- Both in their own bundle
- removed from the legacy bundle.
=> There happened some mistakes regarding the new js resources

docs/HISTORY.txt, ftw/simplelayout/browser/anchors.py
In some cases it was not possible for the current implementation to get
the anchors. With this implementation it is more explicit about the
anchors and is more robust.
=> Fix a tag anchor retrieval

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/galleryblock.py, ftw/simplelayout/contenttypes/browser/templates/galleryblock.pt, ftw/simplelayout/contenttypes/contents/galleryblock.py, ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/fr/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout.pot
- A new option is given to the user, whether the description of the image is used a caption in the overlay or not. 
- The option is enabled by default
- If there's no description and the option is enable it falls back to the old implementation (shows the alt text of the image as caption in the overlay.
=>  Galleryblock: show image description as caption.

docs/HISTORY.txt, ftw/simplelayout/staging/staging.py, ftw/simplelayout/tests/test_staging.py
The same approach is taken as in here:, by moving all items to top it updates and preserves the correct order.
https://github.com/4teamwork/ftw.simplelayout/blob/6781711d351714a0f7a9255c2a8a855ea7c466ab/ftw/simplelayout/configuration.py#L208-L212
=> Preserve children's children order when applying working copies

docs/HISTORY.txt, ftw/simplelayout/staging/staging.py, ftw/simplelayout/tests/test_staging.py
Preserve children's children order when applying working copies
=> Backport 2.x -> 1.x: #541 from ne/preserver-order-in-working-copy

docs/HISTORY.txt, ftw/simplelayout/staging/staging.py
=> Backport 2.x > 1.x - Fix EventBasic timezone conflict when applying working copies (#543)

README.rst
- "introduced Plone 5 support" instead of "introduced Plone support" (missing 5)
- simp**le**layout instead of simp**el**layout
=> Fix support notice for plone 5

docs/HISTORY.txt, ftw/simplelayout/contenttypes/hooks.py, ftw/simplelayout/contenttypes/profiles/default_plone5/registry.xml, ftw/simplelayout/contenttypes/upgrades/20191029182332_add_missing_image_scale/registry.xml, ftw/simplelayout/contenttypes/upgrades/20191029182332_add_missing_image_scale/upgrade.py
The image scale for the big image shown when clicking on a galleryblock
item was missing.
=> Fix galleryblock on click no big image available

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/dropzone.py
Files should be saved as blobs and not in the database as binary data.
This also fixes a bug that with images that are rotated via
exif:Orientation. When saving images as NamedImage the rotation fix by
plone.namedfile was not applied correctly, when using NamedBlobImage
though this works like a charm and fixes the images rotation.
=> Save file as blobs

docs/HISTORY.txt, setup.py
collective.quickupload was replaced with dropzone.js in version 2.0.0
=> Remove collective.quickupload dependency for plone4

docs/HISTORY.txt, ftw/simplelayout/profiles/lib-plone5/metadata.xml, ftw/simplelayout/profiles/lib/metadata.xml
Essential features provided by ftw.simplelayout are not working without the profile ftw.theming:default. Therefore it makes sence to add it to the profiles installed on initialization. I do not add an upgrade step based on the assumption that existing installations using ftw.simplelayout solved the problem already.
=> Add ftw.theming:default profile.

docs/HISTORY.txt, ftw/simplelayout/browser/ajax/edit_block.py
In plone 4 the "Save" from `PloneMessageFactory` translates to "Sichern" whereas the rest of plone uses "Speichern" from `plone.dexterity.i18n`. So we use this as well to make sure the "Save" message is the same across the site and across plone versions.
=> Fix save translation to match the rest of plone in plone 4 / 5

ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/fr/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout.pot, ftw/simplelayout/staging/templates/baseline_viewlet.pt, ftw/simplelayout/staging/templates/workingcopy_viewlet.pt, ftw/simplelayout/staging/viewlets.py, ftw/simplelayout/tests/test_staging.py
- Add a link from working copy to baseline
- Instead of showing the full URL of the working copy on the baseline, show an a tag with linking to the working copy
DE working copy ==> baseline
EN baseline ==> working copy
=> Improve linking between baseline and working copy

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/leadimage.py
This makes it possible for `ftw.events` and `ftw.news` to change the direction to "thumbnail" so that the image is scaled differently.
Backport: https://github.com/4teamwork/ftw.simplelayout/pull/560
=> Leadimage: support changing the scale direction in the view call.

README.rst, docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/dropzone.py, ftw/simplelayout/testing.py, ftw/simplelayout/tests/test_dropzone_upload.py, setup.py
Make the upload widget in FileListingBlock choose the content type it creates based on it's `allowed_content_types`.
Part of the solution to https://github.com/4teamwork/izug.organisation/issues/1620
=> Fix upload to FileListingBlock for ftw.file.File

docs/HISTORY.txt, ftw/simplelayout/mapblock/profiles/default/metadata.xml, ftw/simplelayout/mapblock/profiles/default_plone5/metadata.xml, ftw/simplelayout/mapblock/profiles/uninstall/types/ftw.simplelayout.ContentPage.xml
Mapblock is only used when contenttypes are installed also. Therefore it would be nice if there is a dependency so that when mapblock is getting installed also the contenttypes are getting installed.
This is particularly useful when we need to add mapblock as a dependency in another package where we otherwise had to put both instead of just one.
TODO:
```
AssertionError: u'Index: types/ftw.simplelayout.ContentPage.xml\n=============================== [truncated]... != ''
- Index: types/ftw.simplelayout.ContentPage.xml
- ===================================================================
- --- types/ftw.simplelayout.ContentPage.xml	2019/11/14 19:23:41.627561 GMT+1
- +++ types/ftw.simplelayout.ContentPage.xml	2019/11/14 19:23:41.627761 GMT+1
- @@ -19,6 +19,7 @@
-    <element …
```
=> Add contenttypes to mapblock profile.

docs/HISTORY.txt, ftw/simplelayout/tests/builders.py
Use `ftw.builder >= 1.12.0` to replace this
=> Remove (AT) LinkBuilder in favour of the one in ftw.builder

docs/HISTORY.txt, ftw/simplelayout/__init__.py
Old versions of ftw.sliderblock depended on this product to require collective.upload, which
is no longer done after version 2.0
Resolves https://github.com/4teamwork/ftw.sliderblock/issues/45
=> Fix dependency issue with ftw.sliderblock

docs/HISTORY.txt, ftw/simplelayout/tests/test_dropzone_upload.py, test-plone-4.3.x.cfg, test-plone-5.1.x.cfg
Close https://github.com/4teamwork/ogb/issues/114
Pinning six does not seem to be necessary. Because it results in a version conflict I unpin it. The version conflict is a result of the release of ftw.testbrowser 2.0.0.
If files are not opened in binary mode testbrowser will fail here with the below error:
https://github.com/4teamwork/ftw.testbrowser/blob/2833d166e0a6b1f10c7d14da3f0560f4d15de868/ftw/testbrowser/form.py#L368
```
'unicode' does not have the buffer interface
```
Here first a broken example and then a working one:
```
file_ = open(Path('whatever.txt').abspath(), 'r')
browser.fill({u'File Fäldli': file_})
```
```
file_ = open(Path('whatever.txt').abspath(), 'rb')
browser.fill({u'File Fäldli': file_})
```
=> Unpin six.

docs/HISTORY.txt
Fix: `(WARNING/2) Bullet list ends without a blank line; unexpected unindent.`
=> Fix history.txt.

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/filelistingblock.py
Close https://github.com/4teamwork/izug.organisation/issues/1708
After a migration of the filelisting block, we had an issue with it to load. The sort_order is expected to be a utf-8 string but we passed in a Unicode string now. This resulted in a list of Falses for every char in the Unicode string instead of one False being returned in https://github.com/zopefoundation/Products.ZCatalog/blob/e751eff05374e7f8b39d59b9b9e16e33fab47e11/src/Products/ZCatalog/Catalog.py#L1085.
=> Fix loading error in filelistingblock.

docs/HISTORY.txt
Because the rebase state wasn't up to date it placed the changelog at the wrong place.
=> Move changelog to the top.

docs/HISTORY.txt, ftw/simplelayout/browser/ajax/templates/add.pt, ftw/simplelayout/browser/ajax/templates/block_delete_confirmation.pt, ftw/simplelayout/browser/ajax/templates/edit_block_form.pt, ftw/simplelayout/browser/resources/integration.theme.scss, ftw/simplelayout/mapblock/browser/resources/mapblock.js
Resolves https://github.com/4teamwork/izug.organisation/issues/1720
Looking somewhat better 
referencewidget could be clearer on styling expandable (traversable) items, but I guess that's a different issue
=> Repair overlay styles

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/leadimage.py, setup.py
We don't want to update ftw.simplelayout on a customer installation to newest version, so I backported the necessary changes.
=> Backport #560

docs/HISTORY.txt, ftw/simplelayout/tests/builders.py, test-plone-4.3.x.cfg
This is otherwise incompatible with ftw.builder > 1.12
=> Remove link builder in 1.x branch

docs/HISTORY.txt, ftw/simplelayout/migration.py
In order to disable the archetypes archetypes schemaextender cache we simply set it to `False`. Our code would then fail. Let's improve that.
=> Make migration more robust.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/videoblock.js
This is a backport of e1392375e96cf3f6575c59555fe16ae9ce6bc522
=> Fix youtube integration. The iframe is now stored in `f` not `a`.

docs/HISTORY.txt, ftw/simplelayout/handlers.py, ftw/simplelayout/tests/test_delete_block.py
Deleting a simplelayout block created within a non-simplelayoutish container used to raise the following error in `ftw.simplelayout.handlers.update_page_state_on_block_remove`:
> TypeError: ('Could not adapt', <SampleNonSimplelayoutContainer at /plone/samplenonsimplelayoutcontainer>, <InterfaceClass ftw.simplelayout.interfaces.IPageConfiguration>)
This was first spotted with `ftw.book.Chapter` (block) and `ftw.book.Book` (container).
=> Fix deletion of blocks within non-simplelayoutish containers

docs/HISTORY.txt, ftw/simplelayout/contenttypes/browser/templates/videoblock_vimeo.pt
This helps styling the iframe sizing with e.g. styles like:
```
.iframe-video-wrapper {
overflow: hidden;
// Calculated from the aspect ration of the content (in case of 16:9 it is 9/16= 0.5625)
padding-top: 56.25%;
position: relative;
}
.iframe-video-wrapper iframe {
border: 0;
height: 100%;
left: 0;
position: absolute;
top: 0;
width: 100%;
}
```
=> Add vimeo video iframe wrapper.

ftw/simplelayout/aliasblock/browser/aliasblock.py, ftw/simplelayout/aliasblock/browser/resources/aliasblock.scss, ftw/simplelayout/aliasblock/browser/templates/aliasblock.pt, ftw/simplelayout/aliasblock/contents/aliasblock.py, ftw/simplelayout/configure.zcml, ftw/simplelayout/tests/test_alias_block.py, test-javascript.cfg
This PR adds rendering another block (referenced to) within the alias block.
=> Render block from other location.

ftw/simplelayout/aliasblock/contents/aliasblock.py
"Parent" as start value results in having the reference browser opening in the current section of the tree. 
- There is no need to set `root_path` if it's the plone root anyway.
=> Aliasblock adjustments

ftw/simplelayout/aliasblock/contents/aliasblock.py, ftw/simplelayout/aliasblock/contents/configure.zcml, ftw/simplelayout/tests/test_alias_block.py
This prevents possible recursions and weird behavior for the editor.
I also adde more understandable error messages then just "Constraint not satisfied".
=> Do not allow to add a reference to a contentpage which contains a aliasblock

ftw/simplelayout/aliasblock/browser/aliasblock.py, ftw/simplelayout/aliasblock/contents/aliasblock.py, ftw/simplelayout/tests/test_alias_block.py
Looks not too bad otherwise 😊 
- I added a `assert_html` helper in order to have a `udiff` output if it differs.
=> Implement rendering of sl page in a alias block.

ftw/simplelayout/aliasblock/browser/aliasblock.py, ftw/simplelayout/aliasblock/browser/templates/aliasblock.pt, ftw/simplelayout/tests/test_alias_block.py
Otherwise the "The block could not be rendered" shows to a author.
=> Show a nicer message if the content is not accessable.

ftw/simplelayout/aliasblock/browser/configure.zcml, ftw/simplelayout/aliasblock/browser/templates/aliasblock_form_viewlet.pt, ftw/simplelayout/aliasblock/browser/viewlet.py, ftw/simplelayout/tests/test_alias_block.py
This fixes the fowling JS error:
=> Add google map js to aliasblock add/edit form. In case the block returns map content this is necessary.

docs/HISTORY.txt, ftw/simplelayout/aliasblock/contents/aliasblock.py, ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/fr/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout.pot, ftw/simplelayout/tests/test_alias_block.py
by forbidding referencing the ContenPage you are creating the block on.
=> Prevent recursion when creating an AliasBlock

docs/HISTORY.txt, ftw/simplelayout/aliasblock/browser/aliasblock.py, ftw/simplelayout/aliasblock/browser/templates/aliasblock.pt, ftw/simplelayout/locales/de/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/fr/LC_MESSAGES/ftw.simplelayout.po, ftw/simplelayout/locales/ftw.simplelayout.pot
When we reference a page we shouldn't tell the user that it is a block.
=> Fix AliasBlock text for link to referenced ContentPage

docs/HISTORY.txt, ftw/simplelayout/aliasblock/browser/templates/aliasblock.pt
`to_path` does not take urls and starting at a different path into
account so we use `absolute_url()` which does.
=> Fix link to referenced object

docs/HISTORY.txt, ftw/simplelayout/configure.zcml, setup.py, test-plone-4.3.x.cfg, test-plone-5.1.x.cfg
The condition used in the zcml comes from ftw.autofeature which actually
does not detect if the extra is installed but if all dependencies of the
extra are installed. Thus it will also result to `True` for extras that
don't have a dependency.
Both `contenttypes` and `aliasblock` extras are empty so the conditions were all for naught.
=> Remove obsolete extras

docs/HISTORY.txt, ftw/simplelayout/opengraph/configure.zcml, ftw/simplelayout/opengraph/ftwlogo/configure.zcml, ftw/simplelayout/opengraph/ftwlogo/og_ftw_logo.py, ftw/simplelayout/tests/test_opengraph.py, setup.py
- ftw.simplelayout has now a soft dep on ftw.logo.
- This fixes the opengraph integration if both are installed. Before og:image returned the hard coded logo.jpg.
=> Add ftw.logo support for plone root opengraph integration.

docs/HISTORY.txt, ftw/simplelayout/opengraph/ftwlogo/og_ftw_logo.py, ftw/simplelayout/tests/test_opengraph.py
The `?` to mark the `r=XXXXXX` as a query parameter was missing. The test succeeded because we did not check the query params nor if the URL actually works. Now we do check the URL by opening it (without the `?` it returns a 404 and the test fails)
=> Fix ftw.logo opengraph integration

docs/HISTORY.txt, ftw/simplelayout/browser/configure.zcml, ftw/simplelayout/browser/tinymce.py, ftw/simplelayout/tests/test_content_types.py
Otherwise on the plone root internal links are broken resp. composed like: `/Plone/resolveuid/...`, which does not get caught by the regex from plone.outputfilters, which expect the relative url to start with a `./` --> `resolveuid_re = re.compile('^[./]*resolve[Uu]id/([^/]*)/?(.*)$')`
=> Fix tinymce prependToUrl value, in order to make internal links work on plone root.

docs/HISTORY.txt, ftw/simplelayout/opengraph/og_site_root.py, ftw/simplelayout/opengraph/og_sl_page.py, ftw/simplelayout/tests/test_opengraph.py
Since we don't use TAL to render the content some signs need to be escaped.
Example if somebody used a double quote in the description:
I adjusted the test data. The assertions do not change since the test browser unescapes those signs again.
But the test would fail with the new data and without the changes.
=> Escape special chars for opengraph title and description.

docs/HISTORY.txt, ftw/simplelayout/browser/ajax/delete_blocks.py
In Plone 4 we get a dict. In Plone 5 we get a list of dicts because the API allows for checking multiple objects at once. https://4teamwork.atlassian.net/browse/OGB-624
=> Fix link integrity check on Plone 5

docs/HISTORY.txt, ftw/simplelayout/browser/resources/integration.theme.scss
These images are 100% wide on small screens (see line 128 and following), so they don't need margin there.
This might seem wide-ranging, but it's the right place to clear it up IMO, 
when would we really want to have margins on 100% width images?
For https://4teamwork.atlassian.net/browse/OGB-672
before
after
=> Remove margin from sl images on small screens

docs/HISTORY.txt, ftw/simplelayout/aliasblock/browser/aliasblock.py, ftw/simplelayout/aliasblock/browser/templates/aliasblock.pt, ftw/simplelayout/tests/test_alias_block.py
This basically avoids completely from having issues rendering the block. 
Either "he content is no longer accessible to you" or "The embedded block does not exist." will be displayed.
A failure while rendering the block does not happen anymore.
Before the code usually broke when it tried to access `isBroken` or `to_object` of None type value.
=> AliasBlock rendering improvements. 

docs/HISTORY.txt, ftw/simplelayout/mapblock/profiles/default_plone5/types/ftw.simplelayout.MapBlock.xml, ftw/simplelayout/mapblock/upgrades/20200910161137_remove_non_behavior_interface_from_fti/types/ftw.simplelayout.MapBlock.xml, ftw/simplelayout/mapblock/upgrades/20200910161137_remove_non_behavior_interface_from_fti/upgrade.py
... if IBlockCoordinates is there
This is deprecated and produces the warning:
```
plone.dexterity.schema No behavior registration found for behavior named: 'collective.geo.geographer.interfaces.IGeoreferenceable'
```
which got raised as something to be fixed in bl.web (see https://4teamwork.atlassian.net/browse/OGB-708)
IBlockCoordinates adds IGeoreferenceable as a marker interface anyway
=> Not necessary to add the plain IGeoreferenceable interface as a behavior 

docs/HISTORY.txt, ftw/simplelayout/contenttypes/profiles/default_plone5/registry.xml, ftw/simplelayout/contenttypes/upgrades/20200929161226_fix_contenttype_jquery_dependency/registry.xml, ftw/simplelayout/contenttypes/upgrades/20200929161226_fix_contenttype_jquery_dependency/upgrade.py
Without the depends on plone our JS was loaded before the
plone-compiled JS. This somehow resulted in require.js loading the
jQuery a second time even though jQuery was already present. Why exactly
this happens and why loading plone as the first script fixes this we
don't know - but it does.
=> Fix loading jquery 2 times and with this creating conflicts

docs/HISTORY.txt, ftw/simplelayout/staging/staging.py, ftw/simplelayout/tests/test_staging.py, test-plone-4.3.x.cfg
This preserves the UUIDS and internal links created within the working
copy are still working.
The major change here is, that if the content gets newly created in the working copy. The UUID will be preserved, since the content gets moved the target page instead of copied over.
=> Move objects to the target if they are created within the working copy.

docs/HISTORY.txt, ftw/simplelayout/images/limits/validators.py
> plone.formwidget.namedfile
> 2.0.10 (2019-12-11)
> Bug fixes:
> 
> - set widget value to z3c.form.interfaces.NOT_CHANGED when the user selects ‘Keep Existing File’ in the widget, so z3c.form understands the field has not changed [flipmcf] (#41)
=> Fix compatibility with Plone 5.1.7+

docs/HISTORY.txt, ftw/simplelayout/handlers.py, ftw/simplelayout/tests/test_copy_contentpage.py
Only updating the configuration of the directly copied page leads to broken page configurations and thus all blocks are thrown into the default slot which should not happen.
=> Update page config is recursively

docs/HISTORY.txt, ftw/simplelayout/browser/resources/videoblock.js
We used an internal API endpoint that can change without preliminary notice. This is exactly what happened. So now we use the correct official endpoint instead.
=> Fix youtube video integration

docs/HISTORY.txt, ftw/simplelayout/staging/staging.py
This happens for example if a file within a listingblock gets modified. 
The _copy_field_values method applies changes from the source to the target but never triggers a reindex.
But fields like Title, SearchableText might have changed and need a reindex.
=> Working copy BugFix: Reindex modified children, since the value may have changed

docs/HISTORY.txt, ftw/simplelayout/aliasblock/profiles/default/metadata.xml
To have this as an explicit dependency makes it really hard to install the Aliasblock after SL has been already installed, since it would apply the whole contenttypes configuration again. 
In real world the SL contenttypes is anyway always installed, otherwise there would be no ContentPage to even add a AliasBlock. 
This change makes it easy to add the aliasblock and its config as an update    to a existing site.
=> Aliasblock Remove explicit dependency on sl contenttypes.

docs/HISTORY.txt, ftw/simplelayout/browser/resources/videoblock.js, test-javascript.cfg, test-plone-4.3.x.cfg, test-plone-5.1.x.cfg
Tests fail due to updates of other packages. As this is meant for an older Plone 4.3 policy which already works as is with 2.0.2 I don't deem it necessary to look into those dependency issues for this backport.
=> Fix youtube video integration BACKPORT 2.0.x

docs/HISTORY.txt, ftw/simplelayout/aliasblock/contents/aliasblock.py, ftw/simplelayout/browser/ajax/delete_blocks.py, ftw/simplelayout/tests/test_alias_block.py
Also add a better title for aliasBlocks.
The incoming ref change only works with Plone 5.
Since the link integrity check in plone 4 does not support DX relations (zc.relations)
=> Check all incoming references upon block deletion. This includes AliasBlocks

docs/HISTORY.txt, ftw/simplelayout/aliasblock/browser/viewlet.py
This case happens if the package once was installed and not properly uninstalled.
The package might be still in the path but has some traces all over.
=> Make rendering the aliasblock add/edit form viewlet more safe
